### ISSUE TITLE
Create an article about cross-platform deployment.

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/CQtDeployer#193]
- [x] Deploy on Linux host for windows and linux 
- [ ] Deploy on Windows host for windows and linux 
- [ ] If task #166 is ready then add articles for mac OS

**Comment by AverSnake** [comment]
Hi, is there any progress in cross-platform documentation? Couldn't figure out any info about it from other documentation and it is the main feature I was looking for in CQtDeployer =(

**Comment by EndrII** [comment]
@AverSnake sorry, but no ...
The crossdeploy works some as general deploy, you just need to build your app for needs platform and run deploy command. 

For example:

on Linux
```
cqtdeployer -bin myWindowsProgramm.exe -qmake /mycrossplatform/byildet/qt/bin/qmake zip
``` 

#Note 
The qifw installer does not support for crossdeploy ...
But you can override custom invoke of binarycreator using wine. 

Example: 
```
cqtedployer -bin winApp.exe -qmake path/to/qmake qif -binarycreator "wine path/to/binarycreator.exe"
```

It should help you.

**Comment by EndrII** [comment]
Article prepared and available on github gists 
https://gist.github.com/EndrII/cdaa015d1af18c0b0875ae6d0c54be31
