### ISSUE TITLE
Проблема сборки

### ISSUE THREAD

**Issue by krab22** [QuasarApp/CQtDeployer#230]
Попытался собрать Ваш продукт...
на qmake -r выдает следующее:
`qmake -r
Cannot read /home/*/Development/Git_Work/CQtDeployer/installer/installerCQtDeployer.pri: No such file or directory
Reading /home/*/Development/Git_Work/CQtDeployer/QuasarAppLib/QuasarApp.pro
Cannot read /home/*/Development/Git_Work/CQtDeployer/QuasarAppLib/QuasarApp.pro: No such file or directory
MAKEFILE_GENERATOR variable not set as a result of parsing : QuasarApp.pro. Possibly qmake was not able to find files included using "include(..)" - enable qmake debugging to investigate more.
Reading /home/*/Development/Git_Work/CQtDeployer/pe/pe-parser-library/pe-parser-library.pro
Cannot read /home/*/Development/Git_Work/CQtDeployer/pe-parser-library.pro: No such file or directory
MAKEFILE_GENERATOR variable not set as a result of parsing : pe-parser-library.pro. Possibly qmake was not able to find files included using "include(..)" - enable qmake debugging to investigate more.
Reading /home/*/Development/Git_Work/CQtDeployer/Deploy/Deploy.pro
Cannot read /home/*/Development/Git_Work/CQtDeployer/QuasarAppLib/QuasarLib.pri: No such file or directory
Cannot read /home/*/Development/Git_Work/CQtDeployer/pe/pe-parser-library/pe-parser-library.pri: No such file or directory
WARNING: Failure to find: ../qtTools/src/shared/winutils/elfreader.cpp
WARNING: Failure to find: ../qtTools/src/shared/winutils/elfreader.h
Reading /home/*/Development/Git_Work/CQtDeployer/CQtDeployer/CQtDeployer.pro
Reading /home/*/Development/Git_Work/CQtDeployer/UnitTests/UnitTests.pro
Reading /home/*/Development/Git_Work/CQtDeployer/tests/TestOnlyC/TestOnlyC.pro
Reading /home/*/Development/Git_Work/CQtDeployer/tests/TestQtWidgets/TestQtWidgets.pro
Reading /home/*/Development/Git_Work/CQtDeployer/tests/TestQMLWidgets/TestQMLWidgets.pro
`
В чем проблема?

**Comment by krab22** [comment]
все просто... :-)
после клонирования необходимо сделать:

- git submodule init
- git submodule update

может добавить это в описание?

**Comment by EndrII** [comment]
Сегодня обновлю документацию.

**Comment by EndrII** [comment]
@krab22 
Документация обновленна, пожайлуйста проверти все ли вас устраивает.
посмотреть правки можно [здесь](https://github.com/QuasarApp/CQtDeployer/pull/232#issuecomment-563094084)
