### ISSUE TITLE
проблемы со сборкой v1.3

### ISSUE THREAD

**Issue by krab22** [QuasarApp/CQtDeployer#231]
`configparser.cpp: В конструкторе «ConfigParser::ConfigParser(FileManager*)»:
configparser.cpp:688:5: ошибка: нет декларации «assert» в этой области видимости
  688 |     assert(_fileManager);`

**Comment by krab22** [comment]
в ветви 1.4 еще появилось:
`extracter.cpp: В конструкторе «Extracter::Extracter(FileManager*, ConfigParser*, DependenciesScanner*)»:
extracter.cpp:400:5: ошибка: нет декларации «assert» в этой области видимости
  400 |     assert(_cqt);
`

**Comment by EndrII** [comment]
такие проблеммы могут возникать если собирать проект с помощью qt который был установлен  из репазитория вашей ОС. 
Пользуйтесь официальной [сборкой](https://www.qt.io/download-qt-installer?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5)
или собирайте qt самостоятельно из исходников.

при вызове qmake четко пропишите путь 


например:
```
~/Qt/5.13.2/gcc_64/bin/qmake -r 
```

**Comment by krab22** [comment]
Пользуюсь официальной сборкой... Qt 5.9.3
Попробовал предложенный Вами вариант запуска qmake 
Проблема не исчезла.
`configparser.cpp: В конструкторе «ConfigParser::ConfigParser(FileManager*, DependenciesScanner*)»:
configparser.cpp:883:5: ошибка: нет декларации «assert» в этой области видимости
  883 |     assert(_fileManager);`

**Comment by EndrII** [comment]
у меня на 5.9.5 тоже была аналогичная проблема 
попробуйте 5.12

**Comment by EndrII** [comment]
если для вас критично важен  qt 5.9 
я могу в течении дня добавить поддержку

**Comment by krab22** [comment]
важен
буду благодарен!

**Comment by EndrII** [comment]
в течении дня будут подготовленны пулреквесты

**Comment by krab22** [comment]
а в релизе не будет бага? assert-ов то в релизе нет
код не смотрел :-)

**Comment by EndrII** [comment]
в данном случае  assert - служит для отладки инициализации, так что собранные релизы не подверженны падению.

**Comment by krab22** [comment]
ок
ждемс  :-)

**Comment by EndrII** [comment]
проверяйте [работу](https://github.com/QuasarApp/CQtDeployer/pull/233)

**Comment by EndrII** [comment]
поскольку у вас жесткая привязка к qt5.9 смею предположить что ваш уровень libc не позволит вам воспользоватся уже готовой сборкой cqtdeployer, 
что сделает не возможным выполнение make deploy.
вы можите попробовать установить из snap-store, но если ваш дистрибутив не поддерживает snap вам придется выполнять deploy этап вручную.
Проще всего это сделать следующим образом.

* устанавливаем cqtdeployer из [установщика](https://github.com/QuasarApp/CQtDeployer/releases/tag/1.3.2).
* заходим в CQtDeployer/1.3/
* заменяем все библиотеки и исполняемые файлы на мобранные вами.

после этотого мы можите смело выполнять 
```
make deploy
```

**Comment by krab22** [comment]
make прошел
скачал инсталляшку на 1.3.2
инсталляшка пытается сделать ссылку в каталог ~/.local/bin
В .local каталога bin нет, соответственно ссылка не создается - ошибка установки - что не есть хорошо.

Проблему решил. make deploy инсталляшку на 1.4. собрал.

make deploy пытается сделать пакет snap. На компе утилит для этого нет, соответственно make deploy оканчивается ошибкой - что не очень хорошо.
Может быть создание sanp-пакета вынести в отдельную команду?

"libc не позволит вам воспользоватся уже готовой сборкой cqtdeployer" - почему?

**Comment by EndrII** [comment]
Да,  пррблема с этапом deploy действительно есть.
С инсталлером тоже. 
В течении дня будет исправлено

**Comment by krab22** [comment]
а зачем Вашей утилите путь к qmake?
как она его использует?

**Comment by EndrII** [comment]
С версии 1.4 он определяется автаматически, вам больше не нужно его прописывать (но это работает только если при сборки был включен RPATH, а он обычно включен в qt) 
сам qmake нужен потому что он знает о всех путях к своим библиотекам, qml, исполняемым файлам, переводам и ресурсам (нужной версии qt).

**Comment by EndrII** [comment]
@ krab22 какой дистрибутив вы используете ?

**Comment by EndrII** [comment]
@krab22  
какую ошибку выдает вам installer 1.3.2 ?

**Comment by EndrII** [comment]
@krab22 
Спасибо за ваш репорт. Инсталер теперь стал лучше отробатовать сценарий инициализации.

**Comment by krab22** [comment]
@EndrII 
в общем то не за что ... :-)
я работаю на Fedora 31

**Comment by EndrII** [comment]
тогда это не имеет смыла, просто утановите любым способом cqtdeployer 
```
    устанавливаем cqtdeployer из установщика.
    заходим в CQtDeployer/1.3/
    заменяем все библиотеки и исполняемые файлы на мобранные вами.
```

**Comment by krab22** [comment]
ок.
спасибо

**Comment by krab22** [comment]
и на последок...
в чем разница между версиями 1.3.2 и 1.4.0?
было бы неплохо читать о разнице между версиями в readme...

**Comment by krab22** [comment]
и в качестве идеи:
нужна утилита позволяющая сгенерировать все, что нужно для компиляции инсталляционного файла для проекта - это было бы прикольно!

**Comment by EndrII** [comment]
@krab22 

Список изменений между версиями можно посмотреть в [релизах](https://github.com/QuasarApp/CQtDeployer/releases).
Конкретно списка изменения между 1.3.2 и 1.4.0  пока нет, 1.4 еще не выпущен.
Если вам интересно что будет нового в новом релизе то это можно посмотреть здесь [(еще не реализованные задачи, но запланированные)](https://github.com/QuasarApp/CQtDeployer/milestone/7) и уже [реализованные задачи](https://github.com/QuasarApp/CQtDeployer/milestone/7?closed=1).

Точно так же и для остальных [версий](https://github.com/QuasarApp/CQtDeployer/milestones) 

На счет идеи, не совсем понятно что имеется ввиду.
есть уже похожая [задача](https://github.com/QuasarApp/CQtDeployer/issues/109).

Если это не то что вы хотели просто создайте [новую задачу](https://github.com/QuasarApp/CQtDeployer/issues/new/choose) с полным описанием. 
![image](https://user-images.githubusercontent.com/12465465/70598537-1e2a0400-1bfc-11ea-824e-4d62c04d70a1.png)
