### ISSUE TITLE
Add signature to Windows Installer

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/CQtDeployer#252]

**Comment by EndrII** [comment]
@zig1hai You need to find best offer of application certificate for signing applications.

**Comment by Oleg-designer** [comment]
Most profitable options for buying certificates
https://comodosslstore.com/code-signing https://www.ksoftware.net/code-signing-certificates/

**Comment by EndrII** [comment]
We will not sign our binaries ... if you want to check your downloaded binaries then calc md5 sum and compare it with GitHub [releases](https://github.com/QuasarApp/CQtDeployer/releases) 

``` bash
md5sum CQtDeployer_1.6.2268.24847be_Windows_AMD64.exe 
```
