### ISSUE TITLE
Not deploying platformthemes 

### ISSUE THREAD

**Issue by keshavbhatt** [QuasarApp/CQtDeployer#324]
**Describe the bug**
Deployment step won't copy the platformthemes hence the app not using gtk Filedialog and ColorPicker widget. I don't know if its intentional.
Am using snap version of CQtDeployer.

**To Reproduce**
1. While deploying by running
 `cqtdeployer -bin glate -qmake ~/Qt5.13.0/5.13.0/gcc_64/bin/qmake` 

**Expected behavior**
Copy plateformthemes (and dependencies of lib inside) on Linux

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Comment by EndrII** [comment]
Thanks for the help in finding the problem.

**Comment by EndrII** [comment]
Please check version [1.4.1](https://github.com/QuasarApp/CQtDeployer/releases/tag/1.4.1)


[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/cqtdeployer)

**Comment by keshavbhatt** [comment]
i will thanks for quick fix :+1:

**Comment by EndrII** [comment]
if is it work, close this issue please

**Comment by EndrII** [comment]
I close this issue because now platformthemes is added to the distribution.

**Comment by keshavbhatt** [comment]
sorry i was not able to try it yet. I will confirm tonight. Thanks
