### ISSUE TITLE
Build issue Qt 5.12.6, qset

### ISSUE THREAD

**Issue by RaidenV** [QuasarApp/CQtDeployer#361]
**Describe the bug**
During build from source, step `make -j$(nproc)` fails due to unexpected function call.

**To Reproduce**
1. Follow build for Linux steps in README.md
2. Observe output on step which asks to run command -j$(nproc)

**Expected behavior**
Build to succeed.

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Version 18.04

**Additional context**
filemanager.cpp: In member function ‘void FileManager::loadDeployemendFiles(const QString&)’:
filemanager.cpp:55:82: error: no matching function for call to ‘QSet<QString>::QSet(QList<QString>::iterator, QList<QString>::iterator)’
 deployedFiles.unite(QSet<QString>(deployedFiles.begin(), deployedFiles.end()));
                                                                             ^
In file included from /opt/Qt/5.12.6/gcc_64/include/QtCore/QSet:1:0,
                 from filemanager.h:11,
                 from filemanager.cpp:10:
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:61:12: note: candidate: QSet<T>::QSet(std::initializer_list<_Tp>) [with T = QString]
     inline QSet(std::initializer_list<T> list)
            ^~~~
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:61:12: note:   candidate expects 1 argument, 2 provided
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:59:12: note: candidate: QSet<T>::QSet() [with T = QString]
     inline QSet() Q_DECL_NOTHROW {}
            ^~~~
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:59:12: note:   candidate expects 0 arguments, 2 provided
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:54:7: note: candidate: QSet<QString>::QSet(const QSet<QString>&)
 class QSet
       ^~~~
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:54:7: note:   candidate expects 1 argument, 2 provided
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:54:7: note: candidate: QSet<QString>::QSet(QSet<QString>&&)
/opt/Qt/5.12.6/gcc_64/include/QtCore/qset.h:54:7: note:   candidate expects 1 argument, 2 provided
Makefile:2143: recipe for target 'filemanager.o' failed
make[1]: *** [filemanager.o] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by EndrII** [comment]
Thanks for bug report) 
After successful testing, the changes will go to the master branch.

**Comment by EndrII** [comment]
done, check please

**Comment by RaidenV** [comment]
Confirmed.  Another issue is with the `make deploy` step:

cqtdeployer -bin /home/XXXX/qtdeployer/CQtDeployer/QIFData/../CQtDeployer/build/release clear -qmake /opt/Qt/5.12.6/gcc_64/bin/qmake -libDir /home/XXXX/qtdeployer/CQtDeployer/QIFData/../ -recursiveDepth 4 -ignoreEnv /home/XXXX/qtdeployer/CQtDeployer/QIFData/../CQtDeployer/build/release -targetDir /home/XXXX/qtdeployer/CQtDeployer/QIFData/packages/cqtdeployer.1_4/data/1.4
make: cqtdeployer: Command not found
Makefile:622: recipe for target 'deploy_dep' failed
make: *** [deploy_dep] Error 127

**Comment by RaidenV** [comment]
Exported path including CQtDeployer/build/release, comes back with error loading shared libraries.
Added the following folders to the library path:

/home/XXXX/qtdeployer/CQtDeployer/QuasarAppLib/build/release/
/home/XXXX/qtdeployer/CQtDeployer/Deploy/build/release/
/home/XXXX/qtdeployer/CQtDeployer/pe/pe-parser-library/build/release/

Now compiles.  Perhaps write a bash script for doing this automatically?

**Comment by EndrII** [comment]
> Confirmed. Another issue is with the make deploy step:

#this command requires installed cqtdeployer. Just install cqtdeployer from snap or from installer of github releases.

**Comment by RaidenV** [comment]
> > Confirmed. Another issue is with the make deploy step:
> 
> #this command requires installed cqtdeployer. Just install cqtdeployer from snap or from installer of github releases.
> 
> ```
> sudo snap install cqtdeployer
> ```
> 
> ### Warning:
> 
> If you are building cqtdeployer using qt from your OS repository, use only the cqtdeployer installed from the github installer. The fact is that the snap package does not have access to system libraryes.
> 

This makes no sense.  Why would I be building from source if I already have cqtdeployer installed?  The point is that if I am building from source, you already have the executable built.  This is located in the CQtDeployer/build/release folder... You simply need to add the path, perhaps making this a build step...

> > Update the package version number... With this last bug fix, the version was bumped from 1.4 to 1.5 but, when installed, the install folder is 1.4.
> 
> I do not understand what do you mean. At the moment, the latest version is 1.4, 1.5 in development and has not yet been released. All fixes were made for version 1.4. Changes of these fixes have been accepted for all future versions. 1.5 and master.

In following the installation steps, what version are we pulling down?  1.4? or 1.5?  I take it as master being the most recent and unstable version available.

**Comment by EndrII** [comment]
> In following the installation steps, what version are we pulling down? 1.4? or 1.5? I take it as master being the most recent and unstable version available.



Best to use 1.4. 1.5 and the master are also tested but not so thoroughly.

> This makes no sense. Why would I be building from source if I already have cqtdeployer installed? The point is that if I am building from source, you already have the executable built. This is located in the CQtDeployer/build/release folder... You simply need to add the path, perhaps making this a build step...



As I understand it, you are build this under a platform where there is no way to install cqtdeployer.

In this case, after receiving the assembly file, you need to manually collect all the dependencies.
``` bash
├── bin
|    ├── cqtdeployer
├── lib
│   ├── libDeploy.so.1  (build from this repository)
│   ├── libicudata.so.56 (Qt)
│   ├── libicui18n.so.56 (Qt)
│   ├── libicuuc.so.56 (Qt)
│   ├── libpe-parser-library.so.1 (build from this repository)
│   ├── libQt5Core.so.5 (Qt)
│   └── libQuasarApp.so.1  (build from this repository)
|  cqtdeployer.sh
```

And create run script:

cqtdeployer.sh
``` bash
#!/bin/sh
BASE_DIR=$(dirname "$(readlink -f "$0")")
export LD_LIBRARY_PATH="$BASE_DIR"/lib/:"$BASE_DIR":$LD_LIBRARY_PATH
export QTDIR="$BASE_DIR"
"$BASE_DIR"/bin/cqtdeployer "$@"
```

After this create a symbol link for cqtdeployer.sh in system "/home/.local/bin" or "usr/bin" or "/bin"

```
ln -s cqtdeployer.sh /usr/bin/cqtdeployer
```

And if you want you can repeat the "deploy" step then the manually buildet cqtdeployer will build the full distribution.

But most likely it will not work to build the installer because the system will not have "qt installer framework"

So the distribution will be in CQtDeployer/QIFData/packages/cqtdeployer.1_4/data/1.4

**Comment by EndrII** [comment]
If you succeed. Could you create a script for the deploy without cqtdeployer and create the pull request for this repository?

**Comment by RaidenV** [comment]
> If you succeed. Could you create a script for the deploy without cqtdeployer and create the pull request for this repository?

Yes, absolutely.  I wanted to ask if I could actually go through some of your documentation and correct it grammatically.  I'll update the README.md with the correct wording.  Thank you for all of your work, Enrdll

**Comment by EndrII** [comment]
Yes of course )
I will be very happy for any help, correcting grammatical errors or creating scripts.

**Comment by pzhlkj6612** [comment]
> This makes no sense. Why would I be building from source if I already have cqtdeployer installed? The point is that if I am building from source, you already have the executable built. This is located in the CQtDeployer/build/release folder... You simply need to add the path, perhaps making this a build step...

If environment variable `PATH` contains the paths of Qt and C++ runtime and we can build/generate all files in one directory, this problem will gone. Passing `-after DESTDIR=...` to qmake may be helpful, but I didn't test it.
