### ISSUE TITLE
Whether to search the library specified by extraLibs from libDir

### ISSUE THREAD

**Issue by ZemingLiu** [QuasarApp/CQtDeployer#394]
My configuration is as follows, I need to copy **libMVGigEVisionSDK.so** from **./../HK/Libraries_Linux/64** to the target directory, but after many tests, it has not been successful. 

In issue #367, I find this 
> make cqtdeployer grab the mysql client
uses option extraLibs and extractPlugins
extraLibs - will force cqtdeployer to search for the specified library in **all places of the system**.
extractPlugins - will force cqtdeployer to check qt plugin dependencies 

Therefore, I want to confirm whether CQtDeployer will search libDir for libraries specified by extraLibs.

Thanks

```json
{
    "noOverwrite": false,
    "deploySystem": true,
    "clear": true,
    "libDir": [
        "./../HK/Libraries_Linux/64"
    ],
    "extraLibs": [
        "libMVGigEVisionSDK",
    ],
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Tools",
    "noTranslations": true,
    "libOut": "lib",
    "binOut": "bin",
    "verbose": 0
}
```

**Comment by EndrII** [comment]
Hi, thanks for question.


The libDir and extraLibs options only work with target application dependencies, if your target has libMVGigEVisionSDK.so dependencies, then this library will be copied to targetDir.
However, I do not see the -bin or -binDir options in your configuration file that capture targets.

Do you just want to collect the library dependencies of libMVGigEVisionSDK and put it in "./../../Release/Tools" or do you want the library to be added to your application folder?

If you just want to add this library to your application but the application is not dependet of this library, use the next options:

-extraPlugin path/to/libMVGigEVisionSDK.so // your library will be copyed in the plugins folder.
or
-bin path/to/libMVGigEVisionSDK.so // your library will lie next to your executable files.


Exmplae :
Deploy just one library
```json
{
    "bin": "./../HK/Libraries_Linux/64/libMVGigEVisionSDK.so",
    "noOverwrite": false,
    "deploySystem": true,
    "clear": true,
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Tools",
    "noTranslations": true,
    "libOut": "lib",
    "binOut": "bin",
    "verbose": 0
}
```

Deploy project with libMVGigEVisionSDK library.
```json
{
    "bin": "./../myAppExecutable",
    "extraPlugin": "./../HK/Libraries_Linux/64/libMVGigEVisionSDK.so",
    "extractPlugins": true,
    "noOverwrite": false,
    "deploySystem": true,
    "clear": true,
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Tools",
    "noTranslations": true,
    "libOut": "lib",
    "binOut": "bin",
    "verbose": 0
}
```

If your application has an explicit dependency on libMVGigEVisionSDK then you only need to specify the parent directory in -libDir


```json
{
    "bin": "./../myAppExecutable",
    "noOverwrite": false,
    "deploySystem": true,
    "clear": true,
    "libDir": [
        "./../HK/"
    ],
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Tools",
    "noTranslations": true,
    "libOut": "lib",
    "binOut": "bin",
    "verbose": 0
}
```

Pay attention to the fact that I indicated only the parent directory of your libraries, because you added the recursive search phage "recursiveDepth": 3, which automatically puts on the right library of the architecture you need.

I also see that you are using the deploySystem option, when using this option I can’t guarantee the stability of your final application, as well if you use the cqtdeployer from the snap-store this option will not work correctly.

**Comment by EndrII** [comment]
As for the **extraLibs** option, this option is intended for forced copying of dependencies from the system environment similar to **deploySystem**. The difference is that **deploySystem** copies all the dependencies of the target application (recursive), and **extraLibs** copies only those that match the arguments of this option.

**Comment by EndrII** [comment]
@ZemingLiu  Is your problem solved?

**Comment by ZemingLiu** [comment]
Sorry for late reply.

My application depends on libMVGigEVisionSDK, but there is no indication. I tried using the extraPlugin option, and can see that libMVGigEVisionSDK was copied to the plugin directory.But because the plugin directory is not in LD_LIBRARY_PATH, the program cannot find libMVGigEVisionSDK.

**deployment configurations**
```shell
{
    "bin": "./../Camera_Tools",
    "extraPlugin": "./../HK/Libraries_Linux/64/libMVGigEVisionSDK.so",
    "extractPlugins": true,
    "noOverwrite": false,
    "deploySystem": true,
    "clear": true,
    "libDir": [
        "./../HK/Libraries_Linux/64",
        "/usr/local/lib"
    ],
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Tools",
    "noTranslations": true,
    "libOut": "lib",
    "binOut": "bin",
    "verbose": 0
}
```
**Camera_Tools.sh**
```shell
#!/bin/sh
BASE_DIR=$(dirname "$(readlink -f "$0")")
export LD_LIBRARY_PATH="$BASE_DIR"/lib/:"$BASE_DIR":$LD_LIBRARY_PATH
export QML_IMPORT_PATH="$BASE_DIR"/qml/:$QML_IMPORT_PATH
export QML2_IMPORT_PATH="$BASE_DIR"/qml/:$QML2_IMPORT_PATH
export QT_PLUGIN_PATH="$BASE_DIR"/plugins/:$QT_PLUGIN_PATH
export QTWEBENGINEPROCESS_PATH="$BASE_DIR"/bin/QtWebEngineProcess
export QTDIR="$BASE_DIR"
export QT_QPA_PLATFORM_PLUGIN_PATH="$BASE_DIR"/plugins/platforms:$QT_QPA_PLATFORM_PLUGIN_PATH

"$BASE_DIR"/bin/Camera_Tools "$@"
```

**I change this line** 
```shell
export LD_LIBRARY_PATH="$BASE_DIR"/lib/:"$BASE_DIR":$LD_LIBRARY_PATH
```
**to like it and it worked.**
```shell
export LD_LIBRARY_PATH="$BASE_DIR"/lib/:"$BASE_DIR"/plugins/:"$BASE_DIR":$LD_LIBRARY_PATH
```

Thank you for your quick answer.

**Comment by EndrII** [comment]
Now I understand what you want to do.
Initially, you made the correct configuration.
``` json
{
    "bin": "./../Camera_Tools",
    "noOverwrite": false,
    "deploySystem": true,
    "clear": true,
    "libDir": [
        "./../HK/Libraries_Linux/64",
        "/usr/local/lib"
    ],
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Tools",
    "noTranslations": true,
    "libOut": "lib",
    "binOut": "bin",
    "verbose": 0
}
```
With this configuration, your library should have been copied to lib.

But as I understand it did not happen with your case.

This could have happened for the following reasons:

1. **./../HK/Libraries_Linux/64** - the path may be incorrect, the path must be relative to the configuration file.
2. If you are using snap version of cqtdeployer application and **./../HK/Libraries Linux/64** path is not permitted for package. This can be fixed using the [installer](https://github.com/QuasarApp/CQtDeployer/releases/download/1.4.5/LinuxInstaller.run) version. At the moment, there is a discussion about solving the problems of the snap version. #368 and [snap forum](https://forum.snapcraft.io/t/how-to-access-system-libraries-lib-and-usr-lib-read-only/18862)

**Comment by ZemingLiu** [comment]
Sorry for my poor English.

I use installer version, not snap version. The path **./../HK/Libraries_Linux/64** is correct.

My application depends on libMVGigEVisionSDK, but when using ldd to view dependencies, it is not in the dependency list.Therefore CQtDeployer will not copy libMVGigEVisionSDK to the lib directory.

At present, I have written a shell script, execute CQtDeployer packaging in the script, and after the packaging is completed, copy libMVGigEVisionSDK to the lib directory.

```shell
cd ../
mkdir -p build && cd build
qmake ../
make -j$(nproc)
cqtdeployer -confFile ../Deployer/deployer_linux.json
cp -r ../HK/Libraries_Linux/64/* ../../Release/Camera_Tools/lib
cp -r ../ConfigFiles/config.json ../../Release/Camera_Tools
```

**Comment by EndrII** [comment]
Your problem needs to be dealt with separately, why it so happened that the required library to run is not listed in the dependency list.

Now I can offer you this:

``` json
{
    "bin": [
         "./../Camera_Tools",
         "./../HK/Libraries_Linux/64/libMVGigEVisionSDK.so"
         ],
    "noOverwrite": false,
    "deploySystem": true,
    "clear": true,
    "libDir": [
        "/usr/local/lib"
    ],
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Tools",
    "noTranslations": true,
    "libOut": "lib",
    "binOut": "bin",
    "verbose": 0
}
```

This will force cqtdeployer to copy libMVGigEVisionSDK into lib folder.

**Comment by EndrII** [comment]
if the solution above helped you, please close this discussion.

**Comment by ZemingLiu** [comment]
```shell
"bin": [
         "./../Camera_Tools",
         "./../HK/Libraries_Linux/64/libMVGigEVisionSDK.so"
         ],
```
This will make cqtdeployer not work.

Thank you for your answers. CQtDeployer is a great tool

**Comment by EndrII** [comment]
```
This will make cqtdeployer not work.
```
It’s strange. this should work. Can I see the verbose log?
```
    "verbose": 3
```

**Comment by ZemingLiu** [comment]
```shell
➜  Deployer git:(master) ✗ cat deployer_linux.json 
{
    "bin": [
        "../build/Camera_Tools",
        "../HK/Libraries_Linux/64/libMVGigEVisionSDK.so"
    ],
    "noOverwrite": false,
    "deploySystem": true,
    "deploySystem-with-libc": false,
    "clear": true,
    "force-clear": false,
    "libDir": [
        "./../HK/Libraries_Linux/64",
        "/usr/local/lib"
    ],
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Camera_Tools",
    "noTranslations": true,
    "qmlOut": "qml",
    "libOut": "lib",
    "trOut": "tr",
    "binOut": "bin",
    "recOut": "rec",
    "verbose": 3,
    "qif": false,
    "noCheckRPATH": false,
    "noCheckPATH": false
}
 ➜  Deployer git:(master) ✗ cqtdeployer -confFile deployer_linux.json
Info: Deploy ...

```

**Comment by EndrII** [comment]
try change  
        "../HK/Libraries_Linux/64/libMVGigEVisionSDK.so"
to
        "./../HK/Libraries_Linux/64"

**Comment by ZemingLiu** [comment]
> try change
> "../HK/Libraries_Linux/64/libMVGigEVisionSDK.so"
> to
> "./../HK/Libraries_Linux/64"

Still not working

**Comment by EndrII** [comment]
I think the problem is relative paths.
I draw your attention to the fact that in your configuration file the path begins with "../" which can be interpreted as a path relative to PWD or as an absolute path.

It is important that all paths in the config file start with "./"

``` json
{
    "bin": [
        "./../build/Camera_Tools",
        "./../HK/Libraries_Linux/64/libMVGigEVisionSDK.so"
    ],
    "noOverwrite": false,
    "deploySystem": true,
    "deploySystem-with-libc": false,
    "clear": true,
    "force-clear": false,
    "libDir": [
        "./../HK/Libraries_Linux/64",
        "/usr/local/lib"
    ],
    "recursiveDepth": 3,
    "targetDir": "./../../Release/Camera_Tools",
    "noTranslations": true,
    "qmlOut": "qml",
    "libOut": "lib",
    "trOut": "tr",
    "binOut": "bin",
    "recOut": "rec",
    "verbose": 3,
    "qif": false,
    "noCheckRPATH": false,
    "noCheckPATH": false
}
```

**Comment by ZemingLiu** [comment]
> I think the problem is relative paths.
> I draw your attention to the fact that in your configuration file the path begins with "../" which can be interpreted as a path relative to PWD or as an absolute path.
> 
> It is important that all paths in the config file start with "./"
> 
> ```json
> {
>     "bin": [
>         "./../build/Camera_Tools",
>         "./../HK/Libraries_Linux/64/libMVGigEVisionSDK.so"
>     ],
>     "noOverwrite": false,
>     "deploySystem": true,
>     "deploySystem-with-libc": false,
>     "clear": true,
>     "force-clear": false,
>     "libDir": [
>         "./../HK/Libraries_Linux/64",
>         "/usr/local/lib"
>     ],
>     "recursiveDepth": 3,
>     "targetDir": "./../../Release/Camera_Tools",
>     "noTranslations": true,
>     "qmlOut": "qml",
>     "libOut": "lib",
>     "trOut": "tr",
>     "binOut": "bin",
>     "recOut": "rec",
>     "verbose": 3,
>     "qif": false,
>     "noCheckRPATH": false,
>     "noCheckPATH": false
> }
> ```

I also try this. But still not working.

**Comment by EndrII** [comment]
thanks for reporting the problem)

**Comment by pzhlkj6612** [comment]
> why it so happened that the required library to run is not indicated in the list of dependencies.

It might be a *run-time dynamic linking* library used by [`dlopen`](https://man7.org/linux/man-pages/man3/dlopen.3.html) , [`LoadLibrary`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw) or something equivalent.

Before seeing this post, I had problem with the OpenSSL library. I had to manually copy "libcrypto-1_1-x64.dll" and "libssl-1_1-x64.dll" to the target directory every time. For now, I can use the option "-bin" and "-libDir" like this:

```powershell
> cqt -bin 'path\to\libssl-1_1-x64.dll,myProgram.exe' -libDir 'path\to\the\parent\dir\of\libcrypto-1_1-x64.dll'
```

The library "libssl-1_1-x64.dll" depends on "libcrypto-1_1-x64.dll", so CQtDeployer will copy them together to the target directory. Nice!

However, I never thought I could use the option "-bin" like this and I had no idea why a list can be its value before. This part of the document needs to be improved, in my opinion.

---

And one more thing, the doc said:

> -extraLibs [list,params]
> Sets the mask of the library name for forced copying.
> Example: "-extraLib mySql" - forces to copy all libraries whose names contain mySql to the project folder. This option is case sensitive.

@EndrII explained further:

> As for the **extraLibs** option, this option is intended for forced copying of dependencies from the system environment similar to **deploySystem**.
> https://github.com/QuasarApp/CQtDeployer/issues/394#issuecomment-656678601

It would be better to add the above explanation to the document.

**Comment by EndrII** [comment]
@pzhlkj6612 Thanks, I created a new task to fix the documentation.
