### ISSUE TITLE
Ubuntu 18 to 20 Deployment Issue about libstdc++ / MESA-LOADER

### ISSUE THREAD

**Issue by mkmarineboy** [QuasarApp/CQtDeployer#396]
Hello,

I've been testing my project deployment on Virtual Machines. I'm creating deployment package on Ubuntu 18.04 LTS. on 18 VM it's okay. on 20's VM I get this issue: MESA-LOADER: failed to open swrast

I started to work around  what's causing the issue and found out lib/libstdc++.so.6 file is causing under deployment package's lib folder. I remove this file in custom script Deployment packages worked on both Ubuntu 20 and 18 virtual machines with minimal installations without updates.

I wanted to share this, if it makes sense to developers of C QT Deployer.

Here is my config template configuring by cmake: 

```json {
    "clear": true,
    "deploySystem": true,
    "extractPlugins": true,
    "noCheckRPATH": true,
    "qmlDir": [
        ${JSONQMLDIRS}
    ],
    "qmake": "${CMAKE_SOURCE_DIR}/artifacts/Linux-x86_64/Qt5/bin/qmake",
    "bin": "${CMAKE_BINARY_DIR}/bin/${ARGS_TARGET}",
    "targetDir": "${CMAKE_BINARY_DIR}/qif",
    "libDir": ["${CMAKE_SOURCE_DIR}/artifacts/Linux-x86_64/lib", "${CMAKE_SOURCE_DIR}/3rdparty/missinglibs" ],
    "icon": "${CMAKE_SOURCE_DIR}/src/ksglue/src/theme/theme/images/logo/mPower_light.png",
    "qif": true,
    "deployVersion": "${PROJECT_VERSION}",
    "customScript": "[ ! -e \"$BASE_DIR\"/lib/libstdc++.so.6 ] || rm \"$BASE_DIR\"/lib/libstdc++.so.6"
}
```

**Comment by EndrII** [comment]
Thanks for your report.

**Comment by EndrII** [comment]
Try disable option deploySystem. 

I try not to use this option as conflicts of system libraries on other operating systems are possible.

**Comment by mkmarineboy** [comment]
> @mkmarineboy Try disable the **deploySystem** option.
> 
> I try not to use this option as conflicts of system libraries on other operating systems are possible.

as I remember I was getting qt.gpa plugin error when I didn't use deploySystem option. This is why I was turning this flag on. I'll let you know when I'm available. Thank you for this tool indeed. It's awesome!

**Comment by EndrII** [comment]
@mkmarineboy Thank you for support this utility, this is really cool)

**Comment by EndrII** [comment]
## Solution for developers
To increase the stability of system libraries in Linux, we need to move all system libraries to the '/lib/system' folder and change the boot priorities to:
1. ./lib
2. Host libs
3. ./lib/system

**Comment by EndrII** [comment]
@mkmarineboy Sorry. I was unable to distinguish between system libraries and application libraries. Therefore, as an alternative solution, I simply marked the stdc++ library as not desirable for deployment. This should solve the described problem.
