### ISSUE TITLE
Support Arm64 

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/CQtDeployer#416]
Currently, cqtdeployer can parse Arm32 files.
Need to add support for Arm64

**Comment by EndrII** [comment]
For parsing the ELF library format use an [ELFIO library](https://github.com/QuasarApp/ELFIO?organization=QuasarApp&organization=QuasarApp)

**Comment by aderbas** [comment]
`$ sudo snap install cqtdeployer`
```
error: snap "cqtdeployer" is not available on stable for this architecture (arm64) but exists on
       other architectures (amd64).
```
Not work in Raspberry Pi 4?

**Comment by EndrII** [comment]
@aderbas  Hi, sory but you need to build cqtdeployer from source for ARM platform. In the current time we do not have a complete build for ARM platform. See the issue #199  

You can build cqtdeployer on a x86 host a with cross-platform compiler and deploy project use a CQtDeployer x86 from the Snap store.

**Comment by aderbas** [comment]
Thanks!
