### ISSUE TITLE
"segmentation fault" error at DistributionKit

### ISSUE THREAD

**Issue by avttrue** [QuasarApp/CQtDeployer#417]
OS: KDE Neon 5.19.5
Qt: 5.15
command: "cqtdeployer -bin fungus deploySystem-with-libc noTranslations"
DistributionKit: https://yadi.sk/d/ZrXQdmoMo2ku1Q
"fungus" - application name
Running the application from the build directory (and DistributionKit/bin) is successful, but from the DistributionKit directory results in an error "segmentation fault".
What can you recommend? What is my mistake? Thank.

**Comment by EndrII** [comment]
Hi, thanks for your report.
Please do not use option deploy System-with-libc for gui applications.
Try deploySystem option. It is maybe fix your issue

**Comment by avttrue** [comment]
Hello. Thank you for the answer, it helped me.
`cqtdeployer -bin fungus deploySystem noTranslations`
this is what to need.

**Comment by avttrue** [comment]
But there is another point. It might be better to use a separate topic. I'll explain it here.
Is it possible to introduce support for installing applications on Astra Linux 1.4 and higher?
I tried running my app as a test. I attach the results of the console output.
[astra_ldd.txt](https://github.com/QuasarApp/CQtDeployer/files/5244005/astra_ldd.txt)
[astra_uname.txt](https://github.com/QuasarApp/CQtDeployer/files/5244006/astra_uname.txt)
[log1.txt](https://github.com/QuasarApp/CQtDeployer/files/5244007/log1.txt)

**Comment by EndrII** [comment]
Oh, in the Astra linux very old libc module. 
I have build of the CQTdeployer for Astra linux Smalens 1.5. but current time i am do not have accses to mashin with build.
If I'm lucky, I'll try to get you this assembly on Monday.

**Comment by avttrue** [comment]
If necessary, I have an VirtualBox image of the test system: https://yadi.sk/d/UXKLWJ-suSIU2Q

**Comment by EndrII** [comment]
Special build of The CQtDeployer v1.5.0.2 for astra linux smolensk 1.5 (with libc GLIBC 2.15 )

**Comment by EndrII** [comment]
> If necessary, I have an VirtualBox image of the test system: https://yadi.sk/d/UXKLWJ-suSIU2Q

for astra 1.4 build cqtdeployer is very hard. 
* first you need to build gcc
* second, you need to build qt 5.9 or newer
* thirdly, build the Qt Installer Framework
* and build cqtdeployer with own gcc and own qt.

**Comment by avttrue** [comment]
Thank you!
