### ISSUE TITLE
snap log message "...command not found"

### ISSUE THREAD

**Issue by avttrue** [QuasarApp/CQtDeployer#420]
OS: KDE Neon 5.19.5
Qt: 5.15
command: "cqtdeployer -bin APP_FILE deploySystem noTranslations"
/snap/cqtdeployer/156/bin/desktop-launch: line 163: $'\321\201\321\202\320\276\320\273': command not found

**Comment by EndrII** [comment]
See instructions of install snap for [KDE Neon](https://snapcraft.io/install/cqtdeployer/kde-neon) and after install snapd reboot you system.

And add all requiriment permisions for CQTDeployer.

```
sudo snap connect cqtdeployer:process-control
sudo snap connect cqtdeployer:removable-media
sudo snap connect cqtdeployer:system-backup
```

**Comment by avttrue** [comment]
snap is already installed and no update is required. I issued permissions and rebooted, but the error remained, although the installer is working at first glance.

**Comment by EndrII** [comment]
Did I understand correctly this error occurs in the logs but the application is working correctly?

**Comment by avttrue** [comment]
Yes.
