### ISSUE TITLE
Is it possible to bundle user-editable configuration files?

### ISSUE THREAD

**Issue by gheckman-gadova** [QuasarApp/CQtDeployer#431]
The layout of my build directory looks like:
```
release
├ bin
│  ├ Qml.exe
│  └ Console.exe
├ libs
│  ├ mylib1.so
│  └ mylib2.so
└ config
   ├ config1.ini
   └ config2.ini
```
When I run CQtDeployer, it bundles my bin directory and libs, but I can't figure out how to get my config files into the bundle. I need them in the final installation because they are meant to be edited by the user. Is that possible?

**Comment by EndrII** [comment]
Hi. 
In the current time it is impossible, but you can copy your editable files into bin or plugins location.
## For copy your files into a "bin" location just add them to the "bin" option 

example configFile:
``` json
{
"bin": [
"path/to/config1.ini",
"path/to/config2.ini",
]
}
```

### Result :

``` bash
release
├ bin
│  ├ Qml.exe
│  ├ Console.exe
│  ├ config1.ini
│  └ config2.ini
├ libs
     ├ mylib1.so
     └ mylib2.so

```

## For copy your files into plugins location use a extraPlugins option:

example configFile:
```json
{
"extraPlugins": [
"path/to/config1.ini",
"path/to/config2.ini",
]
}
```
### Result:
``` bash
release
├ bin
│  ├ Qml.exe
│  └ Console.exe
├ libs
│  ├ mylib1.so
│  └ mylib2.so
└ plugins
   ├ config1.ini
   └ config2.ini
```

**Comment by EndrII** [comment]
if this solution doesn't work for you, I could add an option to install additional files.

**Comment by gheckman-gadova** [comment]
Thanks. That will work for now.

**Comment by EndrII** [comment]
i am reopen old task with you problem and close this issue because you have a temp solution. 
Using the bin or extraPlugins options

**Comment by EndrII** [comment]
@gheckman-gadova 

Now in the cqtdeployer 1.5 it is passable. 
You can use the extraData  and extraDataOut options.


Example :

```
cqtdeployer -bin myProject -extraData path/to/config1.ini,path/to/config2.ini -extraDataOut config
```

You can download the cqtdeployer 1.5 from the any online [installer](https://github.com/QuasarApp/CQtDeployer/releases) or from the snap store 
```
sudo snap install cqtdeployer --edge
```

### Warning
cqtdeployer 1.5 is in alpha and may contain undefined bugs.
