### ISSUE TITLE
How to add license?

### ISSUE THREAD

**Issue by haknkayaa** [QuasarApp/CQtDeployer#455]
Hello,
cqtdeployer does it quite nicely. But I want to show the installation program license agreement. After adding the "qif" parameter, I temporarily see the "**Temp Template**" folder, I need to edit the "**config.xml**" directory in it. How can I do this? Is there such a feature?

**Comment by EndrII** [comment]
### Thanks for your question.
## Description 
The CQtDeployer have a solution to your problem. But it is implemented in version 1.5.
at the moment, you cannot automatically forward the license text,
But you can use your own installer template.|

I agree that the license is a widespread requirement for this I put into a separate task the addition of an option with a license.

## Documentation 
As for using your own installer template.
you can read about it [here](https://quasarapp.github.io/CQtDeployer/en/QIF).

## Solution 
And here is a template with a license completely ready for you.
[licenseagreement.zip](https://github.com/QuasarApp/CQtDeployer/files/5581909/licenseagreement.zip)

``` bash
cqtdeployer ...  -qif ./licenseagreement -name Application clear
```


#### It is important that the application name matches the package name of the installer template. For example, I create an installer named Application and my package has the same name.
```
.
├── config
│   ├── config.xml
│   └── controlScript.qs
└── packages
    └── Application
        └── meta
            ├── cc0.txt
            ├── gpl3.txt
            ├── installscript.qs
            └── package.xml

4 directories, 6 files

```

if you want change the application name just use the name option and rename the Application folder from a custom installer.

**Comment by EndrII** [comment]
@haknkayaa i update the documetation of QIF packages. please check the new version of docs. 

if you find errors or you do not understand something please write here.

I will also be very grateful if you fix the errors you found yourself and send a PR with corrections. If you will be fix something, make corrections in the v1.5 branch please.

**Comment by haknkayaa** [comment]
Thank you for reply.

If there is a command, first create the temp template folder. Then continue packaging with the command that will continue for qif to complete. Thus, the default template can be used for very small changes.

**Comment by EndrII** [comment]
> If there is a command, first create the temp template folder. Then continue packaging with the command that will continue for qif to complete. Thus, the default template can be used for very small changes.

You offer create separate command for extract default templates ?

**Comment by haknkayaa** [comment]
> > Bir komut varsa, önce geçici şablon klasörünü oluşturun. Ardından qif'in tamamlaması için devam edecek komutla paketlemeye devam edin. Bu nedenle, varsayılan şablon çok küçük değişiklikler için kullanılabilir.
> 
> Varsayılan şablonları çıkarmak için ayrı bir komut oluşturmayı mı teklif ediyorsunuz?

Exactly. Then I can continue where I left off.

**Comment by haknkayaa** [comment]
> > If there is a command, first create the temp template folder. Then continue packaging with the command that will continue for qif to complete. Thus, the default template can be used for very small changes.
> 
> You offer create separate command for extract default templates ?

Exactly. Then I can continue where I left off.

**Comment by EndrII** [comment]
ok. i am create for this new task see #457 . 
but at the moment you have to use the solution that I suggested above, since the deadline for the task is not defined.

Please write down if everything worked out for you. If everything went well, please close this issue.

**Comment by haknkayaa** [comment]
All right
