### ISSUE TITLE
Minor Russian translation defects in installer

### ISSUE THREAD

**Issue by Amomum** [QuasarApp/CQtDeployer#478]
**To Reproduce**
- Set system language to Russian
- Start installation of CQtDeployer in Windows, using  WindowsOfflineInstaller.exe
- Get to "Выбор компонентов" step
- Observe that text doesn't fit 
- Get to "Всё готово к установке"
- Observe partially translated text; second phrase is in English

**Screenshots**
![image](https://user-images.githubusercontent.com/4990494/102540461-20048e00-40c0-11eb-992b-7a3942134c96.png)

![image](https://user-images.githubusercontent.com/4990494/102540480-26930580-40c0-11eb-8eb9-4be5c558a11a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version  7, 64 bit

**Comment by EndrII** [comment]
Thanks you for your report.
This is minor bugs, and it is bugs of the Qt Installer Framework  therefore, the fixes will not be released soon. but I will try to speed up this process, but I cannot give an exact date.

**Comment by EndrII** [comment]
### Work plan:
1. Clone the QtInstallFramework [repository](https://codereview.qt-project.org/admin/repos/installer-framework/installer-framework) 
2. Prepare a pull request with fixes 
3. Merge all fixes into next release.

**Comment by EndrII** [comment]
A bug report has been sent to Qt.
See the Qt bug tracker [page](https://bugreports.qt.io/browse/QTIFW-2102)

**Comment by EndrII** [comment]
The Qt Installer framework are updated. please check our last [release](https://github.com/QuasarApp/CQtDeployer/releases/tag/1.5.1).
