### ISSUE TITLE
How to package apps build with CQtDeployer into an appimage?

### ISSUE THREAD

**Issue by CRH6F-A-0464** [QuasarApp/CQtDeployer#504]
I successfully generated a working version of my software via CQtDeployer under Debian.  I need to package it into a single AppImage. Any suggestions?

**Comment by EndrII** [comment]
We do not support appimage because appimage has no integration with any OS.

**Comment by EndrII** [comment]
Supports packages:
for version 1.4
* Qt Installer (qif option)


```
cqtdeployer qif -bin MyApp
```


For 1.5 version 
* Qt Installer (qif option)
* independent deb package (deb option)
* and zip arrhive (zip option)


```
cqtdeployer qif deb zip -bin MyApp
```

**Comment by CRH6F-A-0464** [comment]
allright, thanks.
