### ISSUE TITLE
Add description of the bin option.

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/CQtDeployer#520]
> why it so happened that the required library to run is not indicated in the list of dependencies.

It might be a *run-time dynamic linking* library used by [`dlopen`](https://man7.org/linux/man-pages/man3/dlopen.3.html) , [`LoadLibrary`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw) or something equivalent.

Before seeing this post, I had problem with the OpenSSL library. I had to manually copy "libcrypto-1_1-x64.dll" and "libssl-1_1-x64.dll" to the target directory every time. For now, I can use the option "-bin" and "-libDir" like this:

```powershell
> cqt -bin 'path\to\libssl-1_1-x64.dll,myProgram.exe' -libDir 'path\to\the\parent\dir\of\libcrypto-1_1-x64.dll'
```

The library "libssl-1_1-x64.dll" depends on "libcrypto-1_1-x64.dll", so CQtDeployer will copy them together to the target directory. Nice!

However, I never thought I could use the option "-bin" like this and I had no idea why a list can be its value before. This part of the document needs to be improved, in my opinion.

---

And one more thing, the doc said:

> -extraLibs [list,params]
> Sets the mask of the library name for forced copying.
> Example: "-extraLib mySql" - forces to copy all libraries whose names contain mySql to the project folder. This option is case sensitive.

@EndrII explained further:

> As for the **extraLibs** option, this option is intended for forced copying of dependencies from the system environment similar to **deploySystem**.
> https://github.com/QuasarApp/CQtDeployer/issues/394#issuecomment-656678601

It would be better to add the above explanation to the document.

_Originally posted by @pzhlkj6612 in https://github.com/QuasarApp/CQtDeployer/issues/394#issuecomment-774440191_

**Comment by pzhlkj6612** [comment]
@EndrII Hi, don't forget `-extraLibs` . The title needs to be changed.

**Comment by EndrII** [comment]
yes. thanks

**Comment by EndrII** [comment]
@pzhlkj6612 check the #520 PR.
