### ISSUE TITLE
Qml VirtualKeyboard integration - missing to copy a file in plugins folder

### ISSUE THREAD

**Issue by megautier** [QuasarApp/CQtDeployer#549]
**Describe the bug**
On my application, I'm using the VirtualKeyboard from Qt. 
The following file is missing : plugins/platforminputcontexts/libqtvirtualkeyboardplugin.so (which is in $Qt5.15.2_FOLDER/gcc_64/plugins/platforminputcontexts/libqtvirtualkeyboardplugin.so)
I tried to use -extraPlugin  to add the missing file but it is putting it in the plugins folder.
To fix the issue, I'm making a mv plugins/libqtvirtualkeyboardplugin.so plugins/platforminputcontexts/libqtvirtualkeyboardplugin.so

**To Reproduce**
1. Compile and application using the qt virtualkeyboard
2. Use cqtdeployer to generate an exportable application
3. Launch the application
"qrc:/QtQuick/VirtualKeyboard/content/InputPanel.qml:127:5: Type Keyboard unavailable
qrc:/QtQuick/VirtualKeyboard/content/components/Keyboard.qml:38:1: module "QtQuick.VirtualKeyboard.Plugins" is not installed"

**Expected behavior**
The application is launching without need to add manually the library 

**Desktop (please complete the following information):**
 Ubuntu 20.04
local version QT5.15.2

Thanks for the great work on having an easy deploying process.

**Comment by EndrII** [comment]
Hi. Thanks you for bug report.
what cqtdeployer version are you using? 
enter 
```
cqtdeployer v 
```
for check version.

**Comment by megautier** [comment]
Sorry I should have thought to send you also this information : 
cqtdeployer v
CQtDeployer: 1.4.7.1 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed

**Comment by EndrII** [comment]
Спасибо, проверю эту ошибку и исправлю в ближайшее время

**Comment by EndrII** [comment]
Done. Check please version 1.4.7.2.
Do you have a any feedback ?

**Comment by EndrII** [comment]
@megautier 
 i close this issue if you have any feedback then reopen this issues please.

**Comment by megautier** [comment]
I just tested and everything is good.
Thank for the fast fix and efficiency.

**Comment by Ilya-Songrov** [comment]
**I have the same situation.**

_CQtDeployer: 1.4.7.0 has the same error as megautier_

_CQtDeployer: 1.4.7.2 - Ok!_

```
./cqtdeployer.sh v
Info: Print info ...
CQtDeployer: 1.5.0.25 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
```

```
qrc:/QmlFilesServiceModule/QmlServiceModule/MainFileService.qml:2:1: module "QtQuick.Controls" is not installed 
     import QtQuick.Controls 2.15
```

**Comment by EndrII** [comment]
Thanks for you report.

**Comment by EndrII** [comment]
I ran tests on version 1.5 and 1.4 and got the same results.
Both distributions contained an equally correct set of libraries.
But when I tried to start the application, the virtual keyboard did not work for me in both cases. Moreover, every time I run the distribution, my GNOME Shell hangs.
I have not yet been able to figure out what exactly is missing in the distribution. I will continue to deal with this issue tomorrow.

**Comment by EndrII** [comment]
this is trees of the distributions.
[treeCQt14.log](https://github.com/QuasarApp/CQtDeployer/files/6213047/tree14.log)
[treeCQt15.log](https://github.com/QuasarApp/CQtDeployer/files/6213048/tree15.log)

**Comment by EndrII** [comment]
### I found the reason. This is a qml scanner error.
It only checks qml files to extract the dependency tree. However, many qml plugins contain all their qml files already assembled inside the plugin itself with the ***.so** or ***.dll** extension. However, the list of dependencies is written in the **qmldir** descriptor.
So, to ensure the full functionality of the distribution, **cqtdeployer** should be scan **qmlDir** files.

**Comment by EndrII** [comment]
This fix are released in cqtdeployer 1.4.7.3 and 1.5.0.26 versions.
@Ilya-Songrov and @megautier any feedback please.

**Comment by Ilya-Songrov** [comment]
CQtDeployer: 1.5.0.26 still contains the error.

**Comment by Ilya-Songrov** [comment]
_CQtDeployer: **1.5.0.26** still contains the error._

**.pro**
```
QT += quick
QT += quickwidgets
QT += virtualkeyboard

CONFIG += c++11

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Refer to the documentation for the
# deprecated API to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        main.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
```
**main.cpp**
```
#include <QGuiApplication>
#include <QQmlApplicationEngine>


int main(int argc, char *argv[])
{
    qputenv ("QT_IM_MODULE", QByteArray ("qtvirtualkeyboard"));
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    const QUrl url(QStringLiteral("qrc:/main.qml"));
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
        if (!obj && url == objUrl)
            QCoreApplication::exit(-1);
    }, Qt::QueuedConnection);
    engine.load(url);

    return app.exec();
}
```
**main.qml**
```
import QtQml 2.15
import QtQuick 2.15
import QtQuick.Window 2.15
import QtQuick.Controls 2.15
import QtQuick.Controls.Styles 1.4
import QtQuick.VirtualKeyboard 2.3
import QtQuick.VirtualKeyboard.Settings 2.15

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Hello World")



    TextField{
        height: parent.height / 2
        anchors.horizontalCenter: parent.horizontalCenter
    }
    InputPanel {
        z: 2
        y: parent.height / 2
        anchors.left: parent.left
        anchors.right: parent.right
    }
}
```
**run:**
```~/CQtDeployer/1.5/cqtdeployer.sh -bin build-SimpleVirtualKeyboard-Desktop_Qt_5_15_2_GCC_64bit-Debug/SimpleVirtualKeyboard -targetDir CQtDeployKit_SimpleVirtualKeyboard -qmake ~/Qt/5.15.2/gcc_64/bin/qmake -libDir SimpleVirtualKeyboard -recursiveDepth 10 allQmlDependes force-clear```

**Comment by EndrII** [comment]
hmm
@Ilya-Songrov i find one mistake on your command that became the reason of this problem. 
You use the depreciated command **allQmlDependes**. This command will be removed from cqtdeployer 1.5, you should be use the qmlDir command.

### Example:
```
cqtdeployer -bin build-SimpleVirtualKeyboard-Desktop_Qt_5_15_2_GCC_64bit-Debug/SimpleVirtualKeyboard -targetDir CQtDeployKit_SimpleVirtualKeyboard -qmake ~/Qt/5.15.2/gcc_64/bin/qmake -libDir SimpleVirtualKeyboard -recursiveDepth 10 -qmlDir SimpleVirtualKeyboard force-clear
```
This is should be working correctly.

**Comment by Ilya-Songrov** [comment]
Thanks. Your example works!

**Comment by EndrII** [comment]
> Thanks. Your example works!

Thanks for your report.

**Comment by Songrov-ilya** [comment]
**CQtDeployer: 1.5.0.26 still contains the error. 
I created static library that contains virtualkeyboard (VKB). And than i added this library to other poject. And when i deploy my project with cqtdeployer and run it I get this error:**
_qrc:/main.qml:3:1: module "QtQuick.VirtualKeyboard" is not installed 
     import QtQuick.VirtualKeyboard 2.15 
..._

cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.0.26 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed

**Comment by Songrov-ilya** [comment]
**CQtDeployer: 1.5.0.26 still contains the error.
I have created a static library that contains a virtual keyboard (VKB). And then I added this library to another project. And when I deploy my project with cqtdeployer and run it, I get an error like this:**
_qrc:/main.qml:3:1: module "QtQuick.VirtualKeyboard" is not installed
import QtQuick.VirtualKeyboard 2.15
...
..._

```
cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.0.26 *** Binary Box ***
Qt: 5.15.0
QSettings::setValue: Empty key passed
```

**VKB_lib.pro:**
```
QT += quick quickwidgets

CONFIG += c++11
DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += \
        main.cpp

HEADERS += \
    textfieldvkb.h

RESOURCES += qml.qrc

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target


CONFIG(release, debug | release) {
TEMPLATE = lib
DEFINES += PRINTER_LIBRARY
TARGET  = VKB
CONFIG += staticlib
}
```
**textfieldvkb.h:**
```
#pragma once

#include <QDialog>
#include <QQuickWidget>
#include <QGridLayout>

struct InitData{
    InitData(){
        qputenv("QT_IM_MODULE", QByteArray("qtvirtualkeyboard"));
        Q_INIT_RESOURCE(qml); // qml.qrc
    }
};
static const InitData initVirtualkeyboard;



class TextFieldVKB : public QDialog
{
    Q_OBJECT
public:
    explicit TextFieldVKB(QWidget *parent = nullptr) : QDialog(parent), quickWidget(this)
    {
        quickWidget.setSource(QUrl("qrc:/main.qml"));
        QGridLayout *gridLayout = new QGridLayout(this);
        gridLayout->addWidget(&quickWidget);
        gridLayout->setContentsMargins(QMargins());
        this->setLayout(gridLayout);
    }

    void showTextField(){
        exec();
    }

private:
    QQuickWidget quickWidget;
};
```

**main.qml:**
```
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.VirtualKeyboard 2.15

Rectangle {
    id: rectRoot
    width: 640
    height: 480
    color: "coral"

    TextField{
        width: parent.width / 2
        height: parent.height / 10
        anchors.horizontalCenter: parent.horizontalCenter
    }

    InputPanel {
        y: rectRoot.height / 2
        width: rectRoot.width
    }
}
```

**_________________Another test project _________________**
**VKB_lib_test.pro:**
```
QT       += core gui quickwidgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11
DEFINES += QT_DEPRECATED_WARNINGS


SOURCES += \
    main.cpp

qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target


unix:!macx: LIBS += -L$$PWD/ -lVKB
unix:!macx: PRE_TARGETDEPS += $$PWD/libVKB.a

HEADERS += \
    textfieldvkb.h


CONFIG(release, debug | release) {
    QMAKE_POST_LINK=cqtdeployer -bin $${OUT_PWD}/$${TARGET} -targetDir DeployKit_$${TARGET} -qmake $${QMAKE_QMAKE} -libDir $${PWD} \
                            -recursiveDepth 10 -qmlDir $${PWD} force-clear
}
```
**textfieldvkb.h: ↑**

**main.cpp:**
```
#include <QApplication>

#include "textfieldvkb.h"

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    TextFieldVKB textFieldVKB;
    textFieldVKB.showTextField();

    return a.exec();
}
```

**Comment by EndrII** [comment]
@Songrov-ilya Hi
This is a static build. This is not deploy bug. 
I see our code and still cannot find any errors. if I have an idea how to help you, I will write about it.

**Comment by Songrov-ilya** [comment]
> @Songrov-ilya Hi
> This is a static build. This is not deploy bug.
> I see our code and still cannot find any errors. if I have an idea how to help you, I will write about it.

When I build VKB_lib_test and run it, it works without error. But when I deploy this executable with cqtdeployer and run VKB_lib_test.sh it works with errors.
