### ISSUE TITLE
Question about translations

### ISSUE THREAD

**Issue by kartaris** [QuasarApp/CQtDeployer#577]
I've found a file https://github.com/QuasarApp/CQtDeployer/blob/master/QIFData/config/ru.ts
And it is used to translate controlscript.qs as I found. I know that it is converted to the ru.qm file but I can't find where/when it is connected to the installer. May you, please, help me finding it out?

**Comment by EndrII** [comment]
in the current implementation of the installer a translation files not included.
If you want to include the your own qm files for you installer use the translation argument of the config file.
For more information about translate installer see the [official](https://doc.qt.io/qtinstallerframework/qtinstallerframework-translations-example.html) qt documentation.

```
    <Translations>
        <Translation>de.qm</Translation>
        <Translation>pl.qm</Translation>
    </Translations>
```
