### ISSUE TITLE
QtQuick dependancies missing

### ISSUE THREAD

**Issue by simonbagley** [QuasarApp/CQtDeployer#587]
I have tried cqtdeploy on a simple QtQuick application. The package was created successfully and the application can be installed from this. When I try to run the installed application, I get the following errors:
QQmlApplicationEngine failed to load component
qrc:/main.qml:2:1: module "QtQuick.Window" is not installed
qrc:/main.qml:1:1: module "QtQuick" is not installed
qrc:/main.qml:2:1: module "QtQuick.Window" is not installed
qrc:/main.qml:1:1: module "QtQuick" is not installed

The package was created using: cqtdeployer -confFile deployment.json, and the contents of the json file were as follows:
{
    "clear": true,
    "deploySystem": true,
    "extractPlugins": true,
    "noCheckRPATH": false,
    "qif": true,
    "bin": "../build-DeploymentProject-Desktop_Qt_5_15_2_GCC_64bit-Debug/DeploymentProject",
    "qmlDir": ".",
    "qmake": "/home/simon/Qt/5.15.0/gcc_64/bin/qmake",
    "targetDir" : "../DeploymentPackage",
    "allQMlDependes": true
}

The original application created from QtCreator runs ok from QtCreator, and from the command line.

**Comment by simonbagley** [comment]
Linux version: Linux ubuntu 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by EndrII** [comment]
Hi. 
Where you contains your application qml files?
You sets qmlDir to '.' . Your qml files located near  deployment.json ?

**Comment by EndrII** [comment]
**allQMlDependes** option has been deprecated. you need to set qmlDir to the location of the qml files for your project.

**Comment by simonbagley** [comment]
Thanks @EndrII After setting the qmlDir option to point to where my .qml files are and removing the allQmlDependes option, it all works perfectly.
