### ISSUE TITLE
QIF will always be installed even though I didn't select it

### ISSUE THREAD

**Issue by pzhlkj6612** [QuasarApp/CQtDeployer#589]
**Describe the bug**

Qt Installer Framework (QIF) will always be installed with CQtDeployer even though I didn't select it.

**To Reproduce**

1. Download the online or offline installer and execute it. 
2. Don't select the "Qt Installer Framework" component.
3. Continue the installation and note the output in the "details" box.
4. Installation finished. QIF binaries can be found in the "QIF" folder of the installation path.

**Expected behavior**

If QIF is required by CQtDeployer, it should not be deselected when selecting CQtDeployer.

**Output details of installer**

Online installer:

```
Preparing the installation...

Downloading packages...
Downloading archive "4.1.0.2QIF.7z.sha1" for component Qt Installer Framework.
Downloading archive "4.1.0.2QIF.7z" for component Qt Installer Framework.
Downloading archive "1.4.7.31.4.7z.sha1" for component CQtDeployer 1.4.
Downloading archive "1.4.7.31.4.7z" for component CQtDeployer 1.4.

Installing component Qt Installer Framework...
Extracting "4.1.0.2QIF.7z"
Done

Installing component CQtDeployer 1.4...
Extracting "1.4.7.31.4.7z"
Done
Writing maintenance tool.

Installation finished!
```

Offline installer:

```
Preparing the installation...

Installing component Qt Installer Framework...
Extracting "4.0.0QIF.7z"
Done

Installing component CQtDeployer 1.4...
Extracting "1.4.7.01.4.7z"
Done
Writing maintenance tool.

Installation finished!
```

**Environment**

Desktop:
  - Windows 10
    - 1909 10.0.18363.418
    - 2004 10.0.19041.867
  - Ubuntu 20.04.0

**Comment by EndrII** [comment]
Thanks. i will fix it.
