### ISSUE TITLE
Add new Linux release that is just an archive of the files, to run in Docker

### ISSUE THREAD

**Issue by jerkstorecaller** [QuasarApp/CQtDeployer#592]
**Is your feature request related to a problem? Please describe.**
I was creating a Ubuntu 20.04 Docker image to build my Qt 5 project (this is the only way to have an automated build on Bitbucket, Github, Gitlab, etc), and ran into some trouble.

There are 2 options to install CQtDeployer: Ubuntu snap, and the releases on this github project. 

1) Snap/snapd does not work inside Docker images. It's not supported.
2) The installers (LinuxOfflineInstaller.run) don't work either, because they require a graphical stack. I got a segmentation fault.

**Describe the solution you'd like**
I got around it by installing CQtDeployer on my desktop, then compressing the directory ~/CQtDeployer and copying that to my Docker image. 
But it would be better if you just released a .tar.gz file with the program files. 
I think you should do this INSTEAD of the Linux installer: IMO it's pointless to have a GUI installer for a command-line tool, just so you can ask them which directory to install it in. If they know how to use command-line, they can extract it where they want. 

**Describe alternatives you've considered**

**Additional context**

**Comment by EndrII** [comment]
Look our last release please. Now cqtdeployer available in deb, zip packages and the installer support install from terminal or cmd.
https://github.com/QuasarApp/CQtDeployer/releases
