### ISSUE TITLE
qmake not found in Ubuntu 18.04

### ISSUE THREAD

**Issue by facontidavide** [QuasarApp/CQtDeployer#594]
**Describe the bug**

Deployment fails with message:

       Error: The deployment target requir Qt libs, but init qmake is failed.Use the qmake option for set a path to qmake.

Even if the correct qmake option has been provided.

**To Reproduce**
1. On Ubuntu 18.04, check that qmake has been correctly installed with `/usr/bin/qmake --version`. Should return version 5.9.5. 
2. Command to be used: `cqtdeployer -bin <the_app> -qmake /usr/bin/qmake`

**Expected behavior**
Should work? 
Apparently it fails in Ubuntu 18.04 but succeed in Ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Comment by EndrII** [comment]
Hi 
How to you install cqtdeployer tool ?
if you use the snap version please add all permissions.
```bash
    sudo snap connect cqtdeployer:process-control
    sudo snap connect cqtdeployer:removable-media
    sudo snap connect cqtdeployer:system-backup
```

**Comment by EndrII** [comment]
issue closed due to inactivity
