### ISSUE TITLE
Qt5DBus.dll will be deployed even though I didn't use QDBus

### ISSUE THREAD

**Issue by pzhlkj6612** [QuasarApp/CQtDeployer#597]
**Describe the bug**

In Qt 5, "Qt5DBus.dll" will be deployed by CQtDeployer even though I didn't use it in my Qt Widgets app.

**To Reproduce**

1. Create a simple Qt Widgets app (you can use the templates shipped with Qt Creator). Either qmake or CMake can be used.
2. Make sure that this app does not use anything about DBus (QDBus).
3. Build this app.
4. Deploy this app:
    1. Deploy this app via `cqtdeployer.exe -bin path/to/built.exe -qmake path/to/qmake.exe` .
    2. Deploy this app via `windeployqt.exe path/to/built.exe` .
5. Comparing the resulting deployment trees, we can find that "Qt5DBus.dll" is deployed by CQtDeployer only.
6. Try to execute the deployed app without "Qt5DBus.dll" and it works fine.

**Expected behavior**

"Qt5DBus.dll" should not be deployed by CQtDeployer unless I use it.

**Configuration**

- CQtDeployer 1.4.7
- Windows 10 2004 10.0.19041.329
- Qt
  - 5.12.10
  - 5.15.2
  - 6.0.0

**Additional context**

In Qt 6, CQtDeployer doesn't deploy "Qt6DBus.dll" with the same app as above.

**Comment by EndrII** [comment]
Not actually. The Qt5 is deprecated

**Comment by pzhlkj6612** [comment]
Hi.

> Not actually. The Qt5 is deprecated

Hmm, I did not understand what you said. Could you please explain more?

**Comment by EndrII** [comment]
```
Additional context

In Qt 6, CQtDeployer doesn't deploy "Qt6DBus.dll" with the same app as above
```

you say that in qt6 all works correctly. this trouble in qt5 only. Now qt6 is actually version of Qt. So i close this issue because I see no point in fixing this issue...

**Comment by pzhlkj6612** [comment]
OK, got it. Thanks for your reply.
