### ISSUE TITLE
Component missing from installer

### ISSUE THREAD

**Issue by simonbagley** [QuasarApp/CQtDeployer#600]
**Describe the bug**
In Qt 6 I have built the Wayland example called pure-qml, and this works as expected on my build machine, either from Qt creator, or run from the command line. I have used CQtDeployer to create an installer package, but when I install this on another PC, it installs ok, but when I try running the app, it complains about a missing component, and fails to run.

**To Reproduce**
1. In Qt Creator, load the Wayland pure-QML example, and build it. 
2. Change directory to the location where Qt creator places the build. In my case this was: `~/Qt/Examples/Qt-6.1.0/wayland/build-pure-qml-Desktop_Qt_6_1_0_GCC_64bit-Debug`
3. Create a deployment.json file, with contents as shown below
[deployment-json.txt](https://github.com/QuasarApp/CQtDeployer/files/6513847/deployment-json.txt)
4. Run the command `cqtdeployment -confFile deployment.json`
5. Copy the created package folder (DeploymentPackage in my case) to the other PC.
6. On other PC, install the package, by running Installerpure-qml.run
7. On other PC enter the installed package directory, and try running it: cd ~/pure-qml/pure-qml; ./pure-qml.sh

![Qt-6-1-wayland-pure-qml-example](https://user-images.githubusercontent.com/13997517/118938159-42882500-b946-11eb-900f-dd48c0c25a10.png)

**Expected behavior**
I would expect a wayland compositor window to open, within which I could then run other Qt apps.
Instead I get an error message, and the app hangs without showing a window. I then have to do Control-C to exit the app.

**Screenshots**
This is what I get when I try running the installed package:
`simon@ubuntu:~/pure-qml/pure-qml$ ./pure-qml.sh 
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:60:5: Type CompositorScreen unavailable
qrc:/qml/CompositorScreen.qml:58:5: ListModel is not a type
^C
`
This is what I get when running from Qt Creator:
![Run-pure-qml-from-qt-creator](https://user-images.githubusercontent.com/13997517/118941250-6f8a0700-b949-11eb-9719-083519a81c08.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.10
 - uname -a gives: `Linux ubuntu 5.8.0-53-generic #60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
When running the QT Creator generated build from the command line, I get the same result as running from within Qt Creator, as shown in the screenshot above.

**Comment by EndrII** [comment]
Thanks for your report.
I will try to solve this problem within a few days.

**Comment by simonbagley** [comment]
Just to confirm, the PC for build and target are as follows:
Build PC:
Windows 10, running Ubuntu Linux 20.10 in a VMWare Player virtual machine.
lsb_release -a produces:
`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy`

Target PC:
Running Ubuntu Linux 20.10.
lsb_release -a produces:
`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy`

**Comment by EndrII** [comment]
@simonbagley done. This issue solved in the cqtdeployer 1.5. Please update.

**Comment by simonbagley** [comment]
I have just tried this again, with release 1.5, and I get the same error when trying to run the installed application on the target PC:
`simon@ubuntu:~/pure-qml/pure-qml$ ./pure-qml.sh QML debugging is enabled. Only use this in a safe environment. QQmlApplicationEngine failed to load component qrc:/qml/main.qml:60:5: Type CompositorScreen unavailable qrc:/qml/CompositorScreen.qml:58:5: ListModel is not a type ^C`
Maybe it is a problem with me json file?
