### ISSUE TITLE
Installer binary doesn't have product information

### ISSUE THREAD

**Issue by kartaris** [QuasarApp/CQtDeployer#608]
There is no "File description", "Product name", "ProductVersion" in CQtDeployer's installer binary.
Also "File version" contains the version of the QtIFW. 

![image](https://user-images.githubusercontent.com/10552394/119157917-54f58200-ba5e-11eb-9a83-5c61fb4f7aed.png)

**Comment by kartaris** [comment]
My installers looks same. Think it's impossible using current QtIFW's tools(hope i'm wrong).
I want to use [this tool]( https://www.codeproject.com/Articles/37133/Simple-Version-Resource-Tool-for-Windows) to change product information.

**Comment by EndrII** [comment]
This information is added automatically and will not be changed,
If you want to add distributor information, you need to sing your application used Signcode tool.  See https://stackoverflow.com/questions/18287960/signing-windows-application-on-linux-based-distros.
