### ISSUE TITLE
When deploying an qml application with import QtQuick.Shapes 1.12,  application file does not start

### ISSUE THREAD

**Issue by explorer85** [QuasarApp/CQtDeployer#619]
**Describe the bug**
When deploying an qml application with import QtQuick.Shapes 1.12,  application file does not start

**To Reproduce**
Create a simple Qt Quick app (you can use the templates shipped with Qt Creator). 
Add to the main.qml with the following line: import QtQuick.Shapes 1.12
Build this app.
Deploy this app:
C:/Qt/CQtDeployer/1.4/cqtdeployer.bat -bin myapp.exe -qmake D:/Qt1/Qt5.12.10/5.12.10/mingw73_64/bin/qmake.exe -qmlDir D:/Qt1/Qt5.12.10/5.12.10/mingw73_64/qml

Try to execute the deployed app.

**Desktop (please complete the following information):**
CQtDeployer 1.4.7
CQtDeployer 1.5.1
Windows 10 2004 10.0.19041.329
Qt
5.12.10

**Comment by EndrII** [comment]
please update cqtdeployer to 1.5.1 and try deploy your project again

**Comment by explorer85** [comment]
> please update cqtdeployer to 1.5.1 and try deploy your project again

The same situation is repeated when using a cqtdeployer 1.5.1.

**Comment by EndrII** [comment]
I checked this on version cqtdeployer 1.5.1 and all is work correctly. 
i see you set wrong qml path on your run command.

The qmlDir - are root of your qml files, not Qt 
```bah
cqtdeployer -bin myapp.exe -qmake D:/Qt1/Qt5.12.10/5.12.10/mingw73_64/bin/qmake.exe -qmlDir my/QmlFolder
```

**Comment by EndrII** [comment]
i close this issue because it is inactive.

**Comment by pvmilk** [comment]
> @explorer85 I checked this on version cqtdeployer 1.5.1 and all is work correctly. i see you set wrong qml path on your run command.
> 
> The qmlDir - are root of your qml files, not Qt
> 
> ```
> cqtdeployer -bin myapp.exe -qmake D:/Qt1/Qt5.12.10/5.12.10/mingw73_64/bin/qmake.exe -qmlDir my/QmlFolder
> ```

This solved my issue. 
```
The qmlDir - are root of your qml files, not Qt
```
