### ISSUE TITLE
Add openssl lib to distro automatically if application uses libQt5Network

### ISSUE THREAD

**Issue by kartaris** [QuasarApp/CQtDeployer#620]
Some Linux distros include `openssl` libraries  incompatible with `libQt5Network`. That's why providing `openssl` with application needed.
I think it can be useful to do it in `cqtdeployer`. I suggest getting the prebuilt version of compatible `openssl` library using `conan` package manager when there is a `libQt5Network` in the application's dependency tree.

**Comment by EndrII** [comment]
hm. i agree, openssl lib should be deployed automatically

**Comment by kartaris** [comment]
Also I think there could be some cases when applications use their own patched OpenSSL. And user must have an option whether use own OpenSSL or not.

**Comment by pzhlkj6612** [comment]
Hi, @EndrII .

> Applications with qt5 i recommends link openssl manually to your applications. This method force your application load openssl library before start application. So QtNetwork can be find ssl libraries and enable crypto features.
> ...

Do you happen to have a demo project about what you said above? I had tried to use `LIBS += -L<path/to/openssl/lib> -lssl -lcrypto` but both Dependency Walker and lucasg/Dependencies told me that no OpenSSL stuff can be found in the dependency tree of my Qt program. Am I missing anything?
