### ISSUE TITLE
Error: Internal error ocurred in smartMoveTargets (configparser.cpp:1538)

### ISSUE THREAD

**Issue by NewtronReal** [QuasarApp/CQtDeployer#636]
It's the first time I use cqtdeployer to deploy my qt project. I installed cqtdeployer from snap store using

    sudo snap install cqtdeployer

Then I ran

    /mnt/NewVolume1/Qt/5.15.2/gcc_64/bin/qmake -config release

To build my project on release mode.

To deploy my application using cqtdeploy I ran

    cqtdeployer -bin ScreenOverLayMeextension -qmake /mnt/NewVolume1/Qt/5.15.2/gcc_64/bin/qmake -qmlDir ./

Then it show me this error

    NewVolume1/Qt/5.15.2/gcc_64/bin/qmake -qmlDir ./
    Info: Deploy ...
    Info: The targetDir option is not used. CQtDeployer will use default target dir :/mnt/NewVolume1/main_file_folder/QtProjects/ScreenOverLayMeextension/DistributionKit
    Info: Deploy only C/C++ libraries because all target applications do not depend on the Qt libraries
    Error: Internal error ocurred in smartMoveTargets (configparser.cpp:1538).
    Error: If you see this message please create a new issue about this problem on the official github page https://github.com/QuasarApp/CQtDeployer/issues/new/choose. 
    Error: Fail to copy targets
    Error: The CQtDeployer fail to deploy application.

Am I doing anything wrong? Or is this a bug?

**Desktop (please complete the following information):**
 - PopOS
 - 20.10

**Comment by EndrII** [comment]
have you added permissions for cqtdeployer?
```
 sudo snap connect cqtdeployer:process-control 
 sudo snap connect cqtdeployer:removable-media
 sudo snap connect cqtdeployer:system-backup
```

**Comment by NewtronReal** [comment]
Oops.. Sorry. I didn't notice those. Thanks that fix my problem.
