### ISSUE TITLE
Modify exec value in .desktop file after installation

### ISSUE THREAD

**Issue by lamlaaaam** [QuasarApp/CQtDeployer#643]
Is there a way to control the value of the exec statement in the .desktop file when creating the installer? Currently the .desktop file exec points to the .sh file, but I would like to prefix it with "bash -ic" for ROS purposes. How can I do this so that I can distribute the installer normally without users having to make this modification themselves?

**Comment by EndrII** [comment]
Hm. I recommender use the **[runScript](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_CustomScripts.html)** option for sets your own run script with your arguments. 

You can use the this scripts templates](https://github.com/QuasarApp/CQtDeployer/tree/main/Deploy/ScriptsTemplates) for override your own script

**Comment by lamlaaaam** [comment]
Thank you for your reply. Just to clarify, I copy the template script, then which part do I change to modify the exec value? Do I change 
`export CQT_RUN_FILE="$BASE_DIR/CQT_BASE_NAME.sh"` 
to
`export CQT_RUN_FILE="bash -ic $BASE_DIR/CQT_BASE_NAME.sh"`?

**Comment by EndrII** [comment]
> Thank you for your reply. Just to clarify, I copy the template script, then which part do I change to modify the exec value? Do I change
> `export CQT_RUN_FILE="$BASE_DIR/CQT_BASE_NAME.sh"`
> to
> `export CQT_RUN_FILE="bash -ic $BASE_DIR/CQT_BASE_NAME.sh"`?

Yes it is should be work.

But 

if the **bash -ic** must contains in desktop file only then you need to [override the default qifw template](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_QIF.html). 

See the **Custom Template for QIF** section.

**Comment by EndrII** [comment]
@lamlaaaam any feedback please

**Comment by lamlaaaam** [comment]
I will try it out today, give me some time :)

**Comment by lamlaaaam** [comment]
> Thank you for your reply. Just to clarify, I copy the template script, then which part do I change to modify the exec value? Do I change
> `export CQT_RUN_FILE="$BASE_DIR/CQT_BASE_NAME.sh"`
> to
> `export CQT_RUN_FILE="bash -ic $BASE_DIR/CQT_BASE_NAME.sh"`?

I tried this, but doesn't work. The .desktop file is unchanged. Will try overriding the qifw template.

**Comment by lamlaaaam** [comment]
I did
`cqtdeployer getDefaultTemplate qif -bin myBin -qmake /myqmakepath/qmake -qmlDir /myqmlstuff/`
then I went into installscript.qs and changed the exec line to include
`"bash -ic" + (the original line)`
then built the installer with
`cqtdeployer -bin myBin -qmake ... -qmlDir ... -qif DistributionKit/defaultQIFWTemplate/`
but the .desktop file still doesn't have the bash -ic

**Comment by lamlaaaam** [comment]
All is good now. I mistyped some commands while building. Thank you for your help :)

**Comment by EndrII** [comment]
> All is good now. I mistyped some commands while building. Thank you for your help :)
> 
> If anyone needs the full solution:
> 
> ```
> cqtdeployer getDefaultTemplate qif -bin myBin -qmake /myqmakepath/qmake -qmlDir /myqmlstuff/
> // Prefix the exec line in installscript.qs with `bash -ic`
> cqtdeployer -bin myBin -qmake ... -qmlDir ... -qif DistributionKit/defaultQIFWTemplate/
> ```

i am close this issue because a solution is found
