### ISSUE TITLE
Help issue with deploy smart copy! need for deployment!!!!!!

### ISSUE THREAD

**Issue by christophseiche** [QuasarApp/CQtDeployer#649]
**Describe the bug**
Info: Deploy ...
Info: clear old data
Info: Clear start!
Error: Internal error ocurred in smartMoveTargets (configparser.cpp:1553).
Error: If you see this message please create a new issue about this problem on the official github page https://github.com/QuasarApp/CQtDeployer/issues/new/choose. 
Error: Fail to copy targets
Error: The CQtDeployer fail to deploy application.

**To Reproduce**
follow this guide https://muhammetkucuk.com/c-qt-deployer-tool-to-deploy-qt-applications/

**Expected behavior**
to build an executable

**Screenshots**

**Desktop (please complete the following information):**
 - ubuntu
 -  18.04

**Additional context**
I want to build this for A jetson AGX xavier and Nano. arm64. any help on doing so ? very little out there ?

**Comment by christophseiche** [comment]
Thank you, I directly downloaded from GIT. I will have a go at doing these commands.
________________________________

Christian Brooks
Seiche Ltd
E: ***@***.***
W: https://www.seiche.com

Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
​Registered in England & Wales No. 03475558, Registered Office: C/O Seiche Group, Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom

 The information contained in this e-mail transmission, and any documents, files or previous e-mail messages attached to it, is privileged and confidential, and solely intended for the use of the individual(s) to whom it is addressed.  If you are not the intended recipient or a person responsible for delivering it to the intended recipient you should not read, copy, distribute or otherwise use the information, and you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited.  If you have received this message in error, please notify sender immediately and delete this e-mail and attached documents.

**Comment by EndrII** [comment]
@christophseiche hm. please send your deploy command and a config.json file if you use it.

**Comment by christophseiche** [comment]
Hi Andrie,

I have tried doing a basic deployment to begin with.
terminal :

  *   cd to path where deployment.json
  *   cqtdeployer -confFile deployment.json
  *
deployment file attached.



________________________________

Christian Brooks
Seiche Ltd
E: ***@***.***
W: https://www.seiche.com

Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
​Registered in England & Wales No. 03475558, Registered Office: C/O Seiche Group, Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom

 The information contained in this e-mail transmission, and any documents, files or previous e-mail messages attached to it, is privileged and confidential, and solely intended for the use of the individual(s) to whom it is addressed.  If you are not the intended recipient or a person responsible for delivering it to the intended recipient you should not read, copy, distribute or otherwise use the information, and you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited.  If you have received this message in error, please notify sender immediately and delete this e-mail and attached documents.

**Comment by christophseiche** [comment]
Thank you 🙂
________________________________

Christian Brooks
Seiche Ltd
E: ***@***.***
W: https://www.seiche.com

Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
​Registered in England & Wales No. 03475558, Registered Office: C/O Seiche Group, Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom

 The information contained in this e-mail transmission, and any documents, files or previous e-mail messages attached to it, is privileged and confidential, and solely intended for the use of the individual(s) to whom it is addressed.  If you are not the intended recipient or a person responsible for delivering it to the intended recipient you should not read, copy, distribute or otherwise use the information, and you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited.  If you have received this message in error, please notify sender immediately and delete this e-mail and attached documents.

**Comment by EndrII** [comment]
@christophseiche show me please your deployment.json file

**Comment by christophseiche** [comment]
Hello Andrei,
I did send as attachment but here is the code.

{
    "clear": true,
    "deploySystem": true,
    "extractPlugins": true,
    "noCheckRPATH": true,
    "qif": true,
    "bin": "/home/seiche-pc/NVS/build-open_cv_test-Desktop-Release",
    "qmlDir": ".",
    "qmake": "/usr/bin/qmake",
    "targetDir" :  "/home/seiche-pc/DeploymentPackage"
}

Kind regards,
Christian
________________________________

Christian Brooks
Seiche Ltd
E: ***@***.***
W: https://www.seiche.com

Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
​Registered in England & Wales No. 03475558, Registered Office: C/O Seiche Group, Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom

 The information contained in this e-mail transmission, and any documents, files or previous e-mail messages attached to it, is privileged and confidential, and solely intended for the use of the individual(s) to whom it is addressed.  If you are not the intended recipient or a person responsible for delivering it to the intended recipient you should not read, copy, distribute or otherwise use the information, and you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited.  If you have received this message in error, please notify sender immediately and delete this e-mail and attached documents.

**Comment by EndrII** [comment]
to be honest, it is not yet clear to me why you get this error. your settings look correct. But I know that such an error occurred only for users whose cqtdeployer did not have access to the files that it needs to deploy. please check the file permissions.

**Comment by christophseiche** [comment]
Thank you I will check 🙂
________________________________

Christian Brooks
Seiche Ltd
E: ***@***.***
W: https://www.seiche.com

Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
​Registered in England & Wales No. 03475558, Registered Office: C/O Seiche Group, Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom

 The information contained in this e-mail transmission, and any documents, files or previous e-mail messages attached to it, is privileged and confidential, and solely intended for the use of the individual(s) to whom it is addressed.  If you are not the intended recipient or a person responsible for delivering it to the intended recipient you should not read, copy, distribute or otherwise use the information, and you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited.  If you have received this message in error, please notify sender immediately and delete this e-mail and attached documents.

**Comment by EndrII** [comment]
fixed in 1.5.4.10
