### ISSUE TITLE
How to deploy for Jetson AGX Xavier or Nano arm64 jetpack

### ISSUE THREAD

**Issue by christophseiche** [QuasarApp/CQtDeployer#650]
really stuck on creating a deployment for How to deploy for Jetson AGX Xavier or Nano arm64 jetpack.

**Comment by EndrII** [comment]
do you build your arm64 application on arm64 host machine or using amd64 and cross-compilers ?

**Comment by christophseiche** [comment]
I have a jetson AGX Xavier I can build and compile my QT application from. Cross-compilers in the future would be ideal, but for now just need to deploy QT application from JETSON xavier 🙂, A step by step how to guid would be great. The assistance would be most greatful.

Kind regards,
Christian
________________________________

Christian Brooks
Seiche Ltd
E: ***@***.***
W: https://www.seiche.com

Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
​Registered in England & Wales No. 03475558, Registered Office: C/O Seiche Group, Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom

 The information contained in this e-mail transmission, and any documents, files or previous e-mail messages attached to it, is privileged and confidential, and solely intended for the use of the individual(s) to whom it is addressed.  If you are not the intended recipient or a person responsible for delivering it to the intended recipient you should not read, copy, distribute or otherwise use the information, and you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited.  If you have received this message in error, please notify sender immediately and delete this e-mail and attached documents.

**Comment by EndrII** [comment]
fixed in 1.5.4.10
