### ISSUE TITLE
crossdeploy not working on Linux (Windows target)

### ISSUE THREAD

**Issue by khozaei** [QuasarApp/CQtDeployer#652]
crossdeploy not working on Debian for windows target. I had cross compile executable that built with mxe project, the sample project had qml for graphical user interface but when the cqtdeployer had run with command below, it only copied the binary file to the target not qml files and not dll libraries found on the target.
```
cqtdeployer -bin qml-sample.exe -qmlDir ui/qml -targetDir /tmp -qmake /usr/bin/qmake.mingw64
```

**To Reproduce**
1. Pull `hivaiot/ci-qt-windows-target:dynamic` docker image to build cross compile for windows
2. Install cqtdeployer using dpkg
3. Run the command like that explained above
4. See the result

**Desktop (please complete the following information):**
 - OS: Debian
 - Version Buster

**Comment by EndrII** [comment]
1. Show me deploy log with the **-verbose 3** option please.
2. Do you linked application as a static or shared build? (for staticly buildet applications a deploy step no needed)

Sorry, bud i can not pull docker image. please share link.

**Comment by khozaei** [comment]
1. You can see log in my gist: [cqtdeployer -verbose 3](https://gist.github.com/khozaei/1e5281ecfcc585e5e6d37f0089c5df38)
2. The application linked with shared libraries.

**Comment by EndrII** [comment]
yes it is a bug. should be fixed in next release.

**Comment by EndrII** [comment]
@khozaei check please new builds https://github.com/QuasarApp/CQtDeployer/pull/655#issuecomment-909066627

**Comment by khozaei** [comment]
Thank you, It works with some missing library dependencies like `libharfbuzz-0.dll` and `libpng16-16.dll`.
You can see verbose 3 result in this gist: [missing dependencies](https://gist.github.com/khozaei/ff039b363a702a3770613bd299f6cec1)

**Comment by EndrII** [comment]
hm try add deploySystem option to your deploy command. 
this option force cqtdeployer copy all matches from your environment

**Comment by khozaei** [comment]
No Deference in result. [log](https://gist.github.com/khozaei/183aae232e35c9711160d75270b0395e)

**Comment by EndrII** [comment]
Where are located missing libraries ?
maybe you can use the -libDir option

**Comment by EndrII** [comment]
fix are released
