### ISSUE TITLE
How can i include qt libs into my deb package qt

### ISSUE THREAD

**Issue by andr1312e** [QuasarApp/CQtDeployer#663]
Solved Thanks

**Comment by EndrII** [comment]
Try this commands :
```bash
cqtdeployer -bin myexecutable -qmake /path/to/qmake -qmlDir /path/to/my/qml/sources deb
```
For more examples see the documentations [page](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_QuickGuide.html).
