### ISSUE TITLE
CQtDeployer and Snap packaging

### ISSUE THREAD

**Issue by MBSadeghzadeh** [QuasarApp/CQtDeployer#665]
I want to build a snap package from my Qt project on Ubuntu 18.04. I know there are lots of way to do it, but I want to make a standalone version of my project with CQtDeployer and then use a dump plugin of sanpcraft to build a snap for me.
Do you think it is possible?

**Comment by EndrII** [comment]
Yes
I pack my application using cqtdeployer. 

What must you do:
1. Prepare snapcraft.yaml for your project with using [dump](https://snapcraft.io/docs/dump-plugin) plugin.
2. Deploy you project using cqtdeployer without pacakges options. (cqtdeployer -bin myApp -qmlDir path/to/myQmlDir -qmake /path/to/qmake )
3. Sets you distributionKit folder as a source in snapcraft.yaml for dump plugin
4. run snaprcaft

**Comment by MBSadeghzadeh** [comment]
Exactly I did those steps but snaps write some warning that you have some dependencies and it says _specify them using path-through and under stage-packages_. I wonder why CQtDeployer does not found those dependencies if they are required for target to run my app.

**Comment by MBSadeghzadeh** [comment]
By the way, my dump package is cross-compiled by qt on an amd64 ubunto for an arm64. The first question is: Can I pack my app using CQtDeployer on amd64 for arm64?
the second question more about sanp and if the answer to the first question is yes, Can I make a snap for arm64 on amd64 with some stage-packages for arm64 on amd64?

**Comment by EndrII** [comment]
> Exactly I did those steps but snap writes some warning that you have some dependencies and you should _specify them using path-through and under stage-packages_. I wonder why CQtDeployer does not found those dependencies if they are required for target to run my app.

cqtdeployer not copy low level libraries like a libc, Because it can lead to a fall. If you deploy all libs into your snap packages (include libc) then your application failed on run because the snapcore pacakge will be contains incompatible libraries with your builded libraries. 
So you need to add all depends libs manualy into snapcraft.ymal file.

If you sets depend into snapcraft.yaml then depend libraryes will be donwloaded from the compatible a repasitory with [snapcore](https://snapcraft.io/core) pacakge.

you can check my [snapcraft.yaml ](https://github.com/QuasarApp/Hanoi-Towers/blob/main/snap/snapcraft.yaml)for simple qml game.

**Comment by MBSadeghzadeh** [comment]
Very good, I also found you post about _hanoi-tower_ on [snap forum](https://forum.snapcraft.io/t/dump-latest-qt-libs/6390/3), very helpful. Have you understood my requirement of cross compiling for arm64?

**Comment by MBSadeghzadeh** [comment]
> Yes
> I pack my application using cqtdeployer.
> 
> What must you do:
> 
> 1. Prepare snapcraft.yaml for your project with using [dump](https://snapcraft.io/docs/dump-plugin) plugin.
> 2. Deploy you project using cqtdeployer without pacakges options. (cqtdeployer -bin myApp -qmlDir path/to/myQmlDir -qmake /path/to/qmake )
> 3. Sets you distributionKit folder as a source in snapcraft.yaml for dump plugin
> 4. run snaprcaft

_Files from the build host were migrated into the snap to satisfy dependencies that would otherwise not be met. This feature will be removed in a future release. If these libraries are needed in the final snap, ensure that the following are either satisfied by a stage-packages entry or through a part:
usr/lib/x86_64-linux-gnu/libXcomposite.so.1
usr/lib/x86_64-linux-gnu/libXcursor.so.1
usr/lib/x86_64-linux-gnu/libXinerama.so.1
usr/lib/x86_64-linux-gnu/libXrandr.so.2
usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
usr/lib/x86_64-linux-gnu/libatspi.so.0
usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2
usr/lib/x86_64-linux-gnu/libcairo.so.2
usr/lib/x86_64-linux-gnu/libdatrie.so.1
usr/lib/x86_64-linux-gnu/libepoxy.so.0
usr/lib/x86_64-linux-gnu/libgdk-3.so.0
usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
usr/lib/x86_64-linux-gnu/libgraphite2.so.3
usr/lib/x86_64-linux-gnu/libgtk-3.so.0
usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
usr/lib/x86_64-linux-gnu/libpixman-1.so.0
usr/lib/x86_64-linux-gnu/libthai.so.0
usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0
usr/lib/x86_64-linux-gnu/libwayland-egl.so.1
usr/lib/x86_64-linux-gnu/libxcb-render.so.0
usr/lib/x86_64-linux-gnu/libxcb-shm.so.0
usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1
usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0
usr/lib/x86_64-linux-gnu/libxkbcommon.so.0_

**Comment by MBSadeghzadeh** [comment]
> > Exactly I did those steps but snap writes some warning that you have some dependencies and you should _specify them using path-through and under stage-packages_. I wonder why CQtDeployer does not found those dependencies if they are required for target to run my app.
> 
> cqtdeployer not copy low level libraries like a libc, Because it can lead to a fall. If you deploy all libs into your snap packages (include libc) then your application failed on run because the snapcore pacakge will be contains incompatible libraries with your builded libraries.
> So you need to add all depends libs manualy into snapcraft.ymal file.
> 
> If you sets depend into snapcraft.yaml then depend libraryes will be donwloaded from the compatible a repasitory with [snapcore](https://snapcraft.io/core) pacakge.
> 
> you can check my [snapcraft.yaml ](https://github.com/QuasarApp/Hanoi-Towers/blob/main/snap/snapcraft.yaml)for simple qml game.

if you have created a package using CQtDeployer which includes Qt packages for your [hanoi-tower](https://github.com/QuasarApp/Hanoi-Towers/blob/main/snap/snapcraft.yaml), why did you include _desktop-qt5_ part again into your yaml file?

**Comment by EndrII** [comment]
> > > Exactly I did those steps but snap writes some warning that you have some dependencies and you should _specify them using path-through and under stage-packages_. I wonder why CQtDeployer does not found those dependencies if they are required for target to run my app.
> > 
> > 
> > cqtdeployer not copy low level libraries like a libc, Because it can lead to a fall. If you deploy all libs into your snap packages (include libc) then your application failed on run because the snapcore pacakge will be contains incompatible libraries with your builded libraries.
> > So you need to add all depends libs manualy into snapcraft.ymal file.
> > If you sets depend into snapcraft.yaml then depend libraryes will be donwloaded from the compatible a repasitory with [snapcore](https://snapcraft.io/core) pacakge.
> > you can check my [snapcraft.yaml ](https://github.com/QuasarApp/Hanoi-Towers/blob/main/snap/snapcraft.yaml)for simple qml game.
> 
> if you have created a package using CQtDeployer which includes Qt packages for your [hanoi-tower](https://github.com/QuasarApp/Hanoi-Towers/blob/main/snap/snapcraft.yaml), why did you include _desktop-qt5_ part again into your yaml file?

The desktop-qt5 extension do not contains any qt library this i just sh wrapper for prepare environment for run application 
see this rope please for get more detail

**Comment by EndrII** [comment]
> > Yes
> > I pack my application using cqtdeployer.
> > What must you do:
> > 
> > 1. Prepare snapcraft.yaml for your project with using [dump](https://snapcraft.io/docs/dump-plugin) plugin.
> > 2. Deploy you project using cqtdeployer without pacakges options. (cqtdeployer -bin myApp -qmlDir path/to/myQmlDir -qmake /path/to/qmake )
> > 3. Sets you distributionKit folder as a source in snapcraft.yaml for dump plugin
> > 4. run snaprcaft
> 
> _Files from the build host were migrated into the snap to satisfy dependencies that would otherwise not be met. This feature will be removed in a future release. If these libraries are needed in the final snap, ensure that the following are either satisfied by a stage-packages entry or through a part: usr/lib/x86_64-linux-gnu/libXcomposite.so.1 usr/lib/x86_64-linux-gnu/libXcursor.so.1 usr/lib/x86_64-linux-gnu/libXinerama.so.1 usr/lib/x86_64-linux-gnu/libXrandr.so.2 usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 usr/lib/x86_64-linux-gnu/libatspi.so.0 usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 usr/lib/x86_64-linux-gnu/libcairo.so.2 usr/lib/x86_64-linux-gnu/libdatrie.so.1 usr/lib/x86_64-linux-gnu/libepoxy.so.0 usr/lib/x86_64-linux-gnu/libgdk-3.so.0 usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 usr/lib/x86_64-linux-gnu/libgraphite2.so.3 usr/lib/x86_64-linux-gnu/libgtk-3.so.0 usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 usr/lib/x86_64-linux-gnu/libpixman-1.so.0 usr/lib/x86_64-linux-gnu/libthai.so.0 usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 usr/lib/x86_64-linux-gnu/libxcb-render.so.0 usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 usr/lib/x86_64-linux-gnu/libxkbcommon.so.0_

All this libraries you must add to stage-packages section. Just search a name for needed package by library name. Note: do not use "dev" packages.

**Comment by EndrII** [comment]
I close this issue because it is inactive.
