### ISSUE TITLE
Question: How to install cqtdeployer in windows docker container?

### ISSUE THREAD

**Issue by kartaris** [QuasarApp/CQtDeployer#681]
Is there a way to install and use prebuilt cqtdeployer in windows docker container?

**Comment by EndrII** [comment]
Hi 
Use the our installer 

### install without gui 
``` bash
wget https://github.com/QuasarApp/CQtDeployer/releases/download/1.5.4.10/CQtDeployer_1.5.4.10_Installer_Win_x86_64.exe
CQtDeployer_1.5.3.0_Installer_Win64.exe install

```
For more information see the [official](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_Build_and_Install.html) documentation page.

**Comment by kartaris** [comment]
It doesn't work actually(
The commmand does not print anything and there is no installed binaries after((
![image](https://user-images.githubusercontent.com/10552394/146548776-0b7501c5-7fc0-469a-9f73-0afbf65bc25c.png)

**Comment by EndrII** [comment]
hm
try run cqtedeployer installer in power shell

**Comment by kartaris** [comment]
> hm try run cqtdeployer installer in power shell

Nothing changed(

Bu we solved the problem. We just archived binaries into zip, uploaded them into container and it works well.
It would be great if you will add the zip version of binaries for windows into github packages.

**Comment by kartaris** [comment]
Found the problem. "--isolation hyperv" keyword should be used in `docker run` command to run x86 applications in windows containers.
