### ISSUE TITLE
Deploy project with QtAV - no video widget

### ISSUE THREAD

**Issue by nicmorais** [QuasarApp/CQtDeployer#682]
**Describe the bug**
I'm trying to deploy a project that includes [QtAv](https://github.com/wang-bin/QtAV), which was succesfully built by Qt Creator. The copyright message shows on console, but there's no video widget. If i try to play something, the application crashes.

**To Reproduce**
1. ` cqtdeployer -bin build-YI-Hack-Player-Desktop_Qt_5_15_2_GCC_64bit-Release/YI-Hack-Player -name YI-Hack-Player -icon YI-Hack-Player/data/icons/logo.svg` (tried also with -libDir)
2. cd into DistributionKit
3. ./YI-Hack-Player.sh
4. Window shows up, with no video widget

**Expected behavior**
The video widget to show up, completely black

**Screenshots**
![](https://i.imgur.com/GbCIqaK.png)
**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 21.10
- Qt Version: 5.15.2

**Comment by nicmorais** [comment]
Fixed by copying libc6.so and then running ./bin/YI-Hack-Player
But this is not right, is it?

**Comment by EndrII** [comment]
If you want to share your app then you should be build on maximum old distribution for example ubuntu 18.04. If you build on ubuntu 21.10 then you distribution kit will works correctly only on Ubuntu 21.10. If Ubuntu 18.04 the you app works correctly on 18.04 - 21.10.

Why you app not works i don't known.
maybe you QtAV lib not copied. Show me you deploy log please.

**Comment by nicmorais** [comment]
Hello Andrei
https://pastebin.com/5nBWMdyZ

**Comment by EndrII** [comment]
i check you deploy log and i can't see copy QtAV lib into your distribution folder. Maybe you include the QtAV library as a plugin ?

if yes then you need to add **-extraPlugin path/to/QtAV.so** to deploy command 
and load this plugin using  [QLibraryInfo::PluginsPath](https://doc.qt.io/qt-5/qlibraryinfo.html#LibraryLocation-enum)

**Comment by nicmorais** [comment]
@EndrII Alright! But how do I load the plugin with such option? I mean, where and how do I put QLibraryInfo::PluginsPath?
Also, my project is [on Github](https://github.com/Yi-Hack-Tools/Yi-Hack-Player) if someone wants to inspect and/or try it.

**Comment by nicmorais** [comment]
@EndrII Andrei, it's solved! I added
I deployed with:
 -extraPlugin /home/nicolas/Qt/5.15.2/gcc_64/lib/libQtAV.so.1,/home/nicolas/Qt/5.15.2/gcc_64/lib/libQtAVWidgets.so.1
And now it runs as expected on both computers! Thanks a lot, I wish a happy new year for you!
