### ISSUE TITLE
Add new option for limitation deployment architecture.

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/CQtDeployer#685]
## Issue 
In current time  bin and plugin options can contains multiple architectures binary files and all binaries will be deployed into distribution. But some times we need to deploy for only one specify architecture.

## Solution 
Need to add a new option **arch** that will be include [ x86, x86_64, arm, arm64] values.
So if this option will be sets for a package then a package must be deploy only libraries that matches with input architectures

**Comment by kartaris** [comment]
CQtDeployer supports cross-deployment?
Haven't known)

**Comment by EndrII** [comment]
> CQtDeployer supports cross-deployment? Haven't known)

yes, you can add to the 'bin' option windows and linux (arm, x86 ...) binaries and cqtdeployer tries find all dependencies of all input binaries files.
