### ISSUE TITLE
Deploy of projec on Qt 5.15.2 does not include libQt5Sql.so.5 even if module used

### ISSUE THREAD

**Issue by lraimondi** [QuasarApp/CQtDeployer#688]
Hi,
I'm on Linux Mint 20. I have a Qt project that contains subdirs. One of the subdir projects uses SQLITE and module is included in .pro 
`Qt += sql`

When project is built the "make install" creates Deploy folder with /bin and /lib as expected. Then I launch cqtdeployer and alla libraries, plugins, etc are correctly added except libQt5Sql.so.5.
if I ldd the executable I see the dependecy on the library still points to the location in Qt distribution, not relative to my path.

I've been building this projecta piece at the time, including modules on the way and they always got included. This is not happening with SQL. Why ? How can I include it ?

Thanks

**Comment by EndrII** [comment]
Hi 
CQtDeployer can search and copy only dependent libraries. if you project is a plugin then you need to copy them manually 
or add to **extraPlugin** option path to your library that use sql. 

```
cqtdeployer -bin myExecutable -extraPlugin myPlugin
```

**Comment by lraimondi** [comment]
Hi, the project itself it is not a plugin, it is a QML project. I have a structure organized in subdir template. The mail project is QML, other projects are libraries. One of this library project uses SQLITE
![QtCreator_1](https://user-images.githubusercontent.com/66834887/155497758-874553ab-19bd-4f98-be72-da7567790d50.png)
.

The `make install` produces an output like such:
![QtCreator_2](https://user-images.githubusercontent.com/66834887/155498152-e6046563-1b30-475b-9142-ca3d6a317de3.png)

Then I move into the Base directory and use CQtDeployer like such:
`cqtdeployer -bin ./bin/RVN -qmake /home/rd/Qt/5.15.2/gcc_64/bin/qmake -qmlDir /home/rd/Documents/_Qt/WI18/WI18_UI/ -targetDir . -extraPlugin /home/rd/Qt/5.15.2/gcc_64/plugins/sqldrivers/`

What I get is this:
![QtCreator_3](https://user-images.githubusercontent.com/66834887/155498871-571bd175-5e3d-47da-9fe4-b25020985d77.png)
and this
![QtCreator_4](https://user-images.githubusercontent.com/66834887/155498890-f227d192-15cd-4580-976b-23aaec1c0263.png)

but still the library pointed is not in the correct position and the project does not work:
![QtCreator_5](https://user-images.githubusercontent.com/66834887/155499177-b8d5ebc0-fd9a-4c01-8e1d-7140c482ff3b.png)

**Comment by EndrII** [comment]
`
Then I move into the Base directory and use CQtDeployer like such:
cqtdeployer -bin ./bin/RVN -qmake /home/rd/Qt/5.15.2/gcc_64/bin/qmake -qmlDir /home/rd/Documents/_Qt/WI18/WI18_UI/ -targetDir . -extraPlugin /home/rd/Qt/5.15.2/gcc_64/plugins/sqldrivers/
`

The target directory not be a parent directory of your project. Because The CQtDeployer will be ignored, all libraries that located in the target Directory.

try this command 

```
cqtdeployer -bin ./bin/RVN -qmake /home/rd/Qt/5.15.2/gcc_64/bin/qmake -qmlDir /home/rd/Documents/_Qt/WI18/WI18_UI/ -targetDir MyDeployedProject -extraPlugin /home/rd/Qt/5.15.2/gcc_64/plugins/sqldrivers/
```

**Comment by EndrII** [comment]
I close this issue because it is inactive.
