### ISSUE TITLE
Impossible generate installer using QIF in version 1.5.4.13

### ISSUE THREAD

**Issue by esleybonomo** [QuasarApp/CQtDeployer#690]
Hello,

I belave that in version 1.5.4.13 there is a bug that unable generate a installer.

Since 2022-03-04, I'm not able generate a isntaller.

I get this error:

**Info: Use a default installer style
Error: /snap/cqtdeployer/242/QIF/binarycreator: error while loading shared libraries: libxcb-icccm.so.4: cannot open shared object file: No such file or directory

Error: message =  
Error: The CQtDeployer fail to Pack application.**

There is a lib in shared lib:

**$ ls -ltr /lib/x86_64-linux-gnu/libxcb-icccm.so*
-rw-r--r-- 1 root root 22464 dez  4  2018 /lib/x86_64-linux-gnu/libxcb-icccm.so.4.0.0
lrwxrwxrwx 1 root root    21 mar 10  2021 /lib/x86_64-linux-gnu/libxcb-icccm.so.4 -> libxcb-icccm.so.4.0.0
lrwxrwxrwx 1 root root    39 mar  7 11:12 /lib/x86_64-linux-gnu/libxcb-icccm.so -> /lib/x86_64-linux-gnu/libxcb-icccm.so.4**

I'm running this command:

**cqtdeployer \
    -bin ./spectrum,./settings.ini,./lib/* \
    -installDirQIFW "@HomeDir@/spectrum/" \
    -disableShortCut settings \
    -qmlDir ../client/ui \
    -icon ../client/images/logos/vmi-icon.png \
    -name app \
    -qmake "$QMAKE" \
    qif \
    -qifOut Installerspectrum \
    -deployVersion "$VERSION"**

Is it possible turn back the version 1.5.4.12 to try it? I need generate a version to client.

In snap and website there isn't old versions:

**snap-id: Dp7o3dq8lLN9sDymRrv2YLFoZI6V7ftz
channels:
  latest/stable:    1.5.4.13 2022-03-03 (242) 70MB -
  latest/candidate: 1.5.4.13 2022-03-03 (242) 70MB -
  latest/beta:      1.5.4.13 2022-03-03 (242) 70MB -
  latest/edge:      1.5.4.13 2022-03-03 (242) 70MB -**

**Comment by EndrII** [comment]
yes, i fix it later. but at now i reset snap version to 1.5.4.12 because this is works correctly.

**Comment by EndrII** [comment]
please make refresh your snaps. 
```
sudo snap refresh
```

**Comment by EndrII** [comment]
check [cqtdeployer 1.5.4.14](https://github.com/QuasarApp/CQtDeployer/releases/tag/v1.5.4.14)
