### ISSUE TITLE
libicu*.so missing from created DistributionKit

### ISSUE THREAD

**Issue by olowo726** [QuasarApp/CQtDeployer#696]
**Describe the bug**
libicu*.so missing from created DistributionKit

**To Reproduce**
$cqtdeployer -bin MyApp
$./DistributionKit/MyApp -> fails with missing libicu*.so

**Expected behavior**
libicu*.so shall be included in lib folder of created DistributionKit

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - Qt version 6.3.0

**Comment by EndrII** [comment]
Hi 
Do you use the Qt 6.3 installed from a Qt Installer or built itself ?

**Comment by EndrII** [comment]
I close this issue because it is inactive.
