### ISSUE TITLE
How to add additional folders to qif installer ?

### ISSUE THREAD

**Issue by R-P-H** [QuasarApp/CQtDeployer#703]
I would like to add some additional folders with files in them to my installer. Previously, in v1.4, I would just copy the folders to the deployed directory and then they would automatically be included inside the installer when it was created.

This is no longer working in v1.5. How should I go about adding additional folders to my installer so that the folder structure remains the same in the installation directory?

For Example, after installing I want:
myInstallationDir\my.exe
myInstallationDir\myOtherFolder\myOtherFile

**Comment by EndrII** [comment]
Hi 
You should use the **extraData** and **extradataOut** options to configure your distribution. For more information, see our [documentations](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_ExtraFiles.html).

I think this is will be good solution for you: 

```bash
cqtdeployer -extraData myOtherFolder,OrMyanotherFile
```

```bash
cqtdeployer -extraData myOtherFolder
```

For get help of option, use next command :
```
cqtdeployer help -extraData '' -extraDataOut ''
```

**Comment by R-P-H** [comment]
> Hi You should use the **extraData** and **extradataOut** options to configure your distribution. For more information, see our [documentations](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_ExtraFiles.html).
> 
> I think this is will be good solution for you:
> 
> ```shell
> cqtdeployer -extraData myOtherFolder,OrMyanotherFile
> ```
> 
> ```shell
> cqtdeployer -extraData myOtherFolder
> ```
> 
> For get help of option, use next command :
> 
> ```
> cqtdeployer help -extraData '' -extraDataOut ''
> ```

Thank-you !
