### ISSUE TITLE
Meet error during "make deploy" progress

### ISSUE THREAD

**Issue by pocketdr** [QuasarApp/CQtDeployer#708]
**Describe the bug**
`dpkg-deb: error: parsing file '/usr/local/src/CQtDeployer/Distro/defaultDEBTemplate/CQtDeployer/DEBIAN/control' near line 7 package 'cqtdeployer':
 blank line in value of field 'Description'`

**To Reproduce**
#706 After pull new code, `make` ran successfully.  
First time when I use `make deploy` it told me that ` cqtdeployer: Command not found`. So I copied cqtdeployer to /usr/bin, and added below Env because there is no  arm installer.
![image](https://user-images.githubusercontent.com/45301505/183798806-02559f91-daa6-4f7a-932d-bea06b9f8289.png)

After that, i got error like this 
`Error: Failed to set libDir path! The /usr/local/src/CQtDeployer/ path will be ignored because this path is child path of the targetDir path or manually added into ignore environment.`
So I changed libDir option on deploy_beb section which in my Makefile been auto created by qmake as follows:
```
...... 
-libDir  /usr/local/src/CQtDeployer/zip/build/release,/usr/local/src/CQtDeployer/pe/pe-parser-library/build/release,/usr/local/src/CQtDeployer/Deploy/build/release,/usr/local/src/CQtDeployer/QuasarAppLib/build/release 
......
```

**Expected behavior**
CQtDeployerInstaller.run

**Screenshots**
![image](https://user-images.githubusercontent.com/45301505/183800190-62a91dc5-8798-4287-8556-ba1a6d6b5439.png)

**Desktop (please complete the following information):**
same as #706 

**Additional context**
When I got the "dpkg-deb-error", I had try to add "-description something" to Makefile on deploy_beb section, but the control file still have blank line after the "Description" line.

**Comment by EndrII** [comment]
hm 
Just try to [install](https://github.com/QuasarApp/CQtDeployer/releases/tag/1.5.4.7) cqtdeployer for arm and try to deploy step again with the default make file

**Comment by pocketdr** [comment]
wow, thx! I don't find it before

**Comment by pocketdr** [comment]
> hm Just try to [install](https://github.com/QuasarApp/CQtDeployer/releases/tag/1.5.4.7) cqtdeployer for arm and try to run a 'deploy' step again with the default make file

It told my that
`/opt/CQtDeployer/bin/cqtdeployer: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /opt/CQtDeployer/lib/libQt5Core.so.5)`

Is it a good idea to update my GLIBC from 2.27 to 2.28?

**Comment by EndrII** [comment]
No, updating libc it is a bad idea, 
The best solution for you will be changing the qmake build file of cqtdeployer and rebuild the project 

You need to change [this](https://github.com/QuasarApp/CQtDeployer/blob/main/QIFData/installerCQtDeployer.pri#L28) line to 
```
BASE_DEPLOY_FLAGS_DEB = $$BASE_DEPLOY_FLAGS -targetDir $$PWD/../Distro $$OUT_LIB $$OUT_BIN zip -name CQtDeployer -publisher QuasarApp $$CQT_ICON -deployVersion 1.5.4.17 CQtDeployer_'$$VERSION'_Linux'_$$QMAKE_HOST.arch'.zip
```

Just remove the creating a deb package.

**Comment by pocketdr** [comment]
Thx! It works! 
The packaged Zip run successfully on the other board with Debian! 

BTW, there should add an option before the name of zip
`-zipOut CQtDeployer_'$$VERSION'_Linux'_$$QMAKE_HOST.arch'.zip`

**Comment by EndrII** [comment]
I close this issue because, I plan to change the build system to cmake. So if somebody has this issue, just disable deb packing on first deploy time.

> No, updating libc it is a bad idea, The best solution for you will be changing the qmake build file of cqtdeployer and rebuild the project
> 
> You need to change [this](https://github.com/QuasarApp/CQtDeployer/blob/main/QIFData/installerCQtDeployer.pri#L28) line to
> 
> ```
> BASE_DEPLOY_FLAGS_DEB = $$BASE_DEPLOY_FLAGS -targetDir $$PWD/../Distro $$OUT_LIB $$OUT_BIN zip -name CQtDeployer -publisher QuasarApp $$CQT_ICON -deployVersion 1.5.4.17 CQtDeployer_'$$VERSION'_Linux'_$$QMAKE_HOST.arch'.zip
> ```
> 
> Just remove the creating a deb package.
