### ISSUE TITLE
How to force overwrite the old installation directory when reinstalling

### ISSUE THREAD

**Issue by laxian** [QuasarApp/CQtDeployer#711]
How to force overwrite the old installation directory when reinstalling
Thank you.

**Comment by EndrII** [comment]
Sorry, but it is qt installer framework [issue](https://stackoverflow.com/questions/21389105/qt-installer-framework-offline-update-how). You can [override](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_QIF.html) qt installer template and add instructions to remove preview builds... but it is not secure, you may break your distributive.

**Comment by laxian** [comment]
Emmm..got it, thank you.
