### ISSUE TITLE
The last version is wrong

### ISSUE THREAD

**Issue by esleybonomo** [QuasarApp/CQtDeployer#728]
Hello,

When I build my application and I have the component DefaultFileDialog.qml, it wil'not be found.

```
Type FileDialog unavailable
file:///usr/local/myapp/qml/QtQuick/Dialogs/DefaultFileDialog.qml:50:1: "qml": no such directory
```

I revert to version 1.5.4.17 and it's OK

Tks,
Esley

**Comment by EndrII** [comment]
Hi, 
Thank you for your report. 
send me more information about your issue. 
* Deployment verbose log 
* Your qml file (imports only)
* Your qt version

**Comment by EndrII** [comment]
@esleybonomo I added new test for qml file dialog, but all works great. 
maybe you use the qt 5 ?
