### ISSUE TITLE
libc.so version problem

### ISSUE THREAD

**Issue by nero08** [QuasarApp/CQtDeployer#735]
Hello, I have a problem when I tried to execute cqtdeployer:

/snap/cqtdeployer/262/bin/CQtDeployer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/cqtdeployer/262/bin/CQtDeployer)
/snap/cqtdeployer/262/bin/CQtDeployer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /snap/cqtdeployer/262/lib/libDeploy.so)
/snap/cqtdeployer/262/bin/CQtDeployer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/cqtdeployer/262/lib/libpe-parse.so)
/snap/cqtdeployer/262/bin/CQtDeployer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /snap/cqtdeployer/262/lib/libpe-parse.so)
/snap/cqtdeployer/262/bin/CQtDeployer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/cqtdeployer/262/lib/libzip.so)

Do you know how to resolve this?

**Comment by EndrII** [comment]
Hm 

Show me output of 
```
ldd --version 
```
and 
```
snap --version
```

**Comment by nero08** [comment]
hello

```
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright © 2020 Free Software Foundation, Inc.
Ce logiciel est libre; voir les sources pour les conditions de
reproduction. AUCUNE garantie n'est donnée; tant pour des raisons
COMMERCIALES que pour RÉPONDRE À UN BESOIN PARTICULIER.
Écrits par Roland McGrath et Ulrich Drepper.

```

```
snap --version
snap       2.57.2
snapd      2.57.2
series     16
linuxmint  20
kernel     5.4.0-131-generic
```

**Comment by EndrII** [comment]
Maybe you install cqtdeployer as a classic app ? 
try remove cqtdeployer 
```
snap remove cqtdeployer
```

And install again 

```
snap install cqtdeployer 
```

**Comment by nero08** [comment]
already did it but nothing change.

Ldd show version 2.31, so my version is outdated?

**Comment by EndrII** [comment]
Yes, but for snap it is not trouble, because cqtdeployer works with libc from the core22... it should be works on all old distributions that support snap ...

**Comment by EndrII** [comment]
I check snapd [documentations](https://snapcraft.io/docs/installing-snapd) and can't found linux mint support. I think it is linux mint isssue ... 

Because I can run cqtdeployer on my old ubuntu distros with very old libc package 


``` bash
root@crack-gnu:~# ldd --version 
ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
root@crack-gnu:~# cqtdeployer v
Info: Print info ...
CQtDeployer: 1.6.2268.24847be *** Cool Core (snap) ***
Qt: 6.4.0
root@crack-gnu:~# 

```

**Comment by EndrII** [comment]
hm, maybe this [article](https://snapcraft.io/docs/installing-snap-on-linux-mint) can help solve your issue

**Comment by nero08** [comment]
finally solve it, I just delete and reinstall snap, thanks for your help
