### ISSUE TITLE
How to copy config files into bin directory

### ISSUE THREAD

**Issue by laxian** [QuasarApp/CQtDeployer#739]
I want to pack some config files into the _bin_ directory,  What should I do?

I've tried the "-bin" option, which didn't work:

```
# cqtdeployer -bin ./build/qt_hmi,./build/config.json -libDir .sdk,libs,cjson -extraLibs "libxcb-xinput,freetype,libpng"
Info: Deploy ...
Info: The targetDir option is not used. CQtDeployer will use default target dir :/var/lib/jenkins/workspace/qt_hmi/default/DistributionKit
Info: copy :/var/lib/jenkins/workspace/qt_hmi/default/build/qt_hmi
Error: Internal error ocurred in smartMoveTargets (configparser.cpp:1559).
Error: If you see this message please create a new issue about this problem on the official github page https://github.com/QuasarApp/CQtDeployer/issues/new/choose.
Error: Fail to copy targets
Error: The CQtDeployer fail to deploy application.
```

Thank you!

**Comment by EndrII** [comment]
Hi, you can use the **extraData** and **extraDataOut** [options](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_ExtraFiles.html)

## Short example for your case:

``` bash
cqtdeployer -bin ./build/qt_hmi -extraData ./build/config.json -extraDataOut bin -libDir .sdk,libs,cjson -extraLibs "libxcb-xinput,freetype,libpng"
```

By default, the extra data will copy into root distribution folder, but you can change it using an extraDataOut option.

**Comment by laxian** [comment]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/13779717/208100830-80dec119-47da-4f01-af94-8b815eb8c37a.png">

@EndrII It works! thank you!
