### ISSUE TITLE
cannot mix incompatible qt library (5.9.5) with this library (5.15.2)

### ISSUE THREAD

**Issue by laxian** [QuasarApp/CQtDeployer#750]
Hi:

My CI server : 
Ubuntu 18.04; QT 5.15.2
QMake version 3.1
Using Qt version 5.15.2 in /opt/qt515/lib

cmake cannot find qtwebengine, so I installed qtwebengine-dev with `apt`. then cmake works. 

It crashed while run on a new Ubuntu PC:
`cannot mix incompatible qt library (5.9.5) with this library (5.15.2)`

Ifound there are two qtwebengine version:

`/home/root/libQt5152/libQt5WebEngineWidgets.so.5.15.2`
`/usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5.9.5`

But it seems it packed the 5.9.5 to the installer.

this is my command:
`cqtdeployer qif -qmake /opt/qt515/bin/qmake -bin ./hmi -libDir ../libs,./cjson/ -extraData ../config.json,../device.pem -extraDataOut bin -extraLibs "libxcb-xinput,freetype,libpng,libevent,libre2,libav,libswresample,libcrystalhd,libx26,libvpx,libcairo,librsvg,libcroco,libQt5"`

How to use the specific first version 5.15.2?
What is the best way to resolve this?
Thanks!

**Comment by EndrII** [comment]
Yes, this very bad idea to mix different qts on one distribution kit. 

So just remove your web engine from APT, 
and try to solve your cmake issue.

**Comment by EndrII** [comment]
i think this issue can't be solved
