### ISSUE TITLE
Latest version can not run on Ubuntu 20 

### ISSUE THREAD

**Issue by Rbcum** [QuasarApp/CQtDeployer#751]
Hi, I've tried to run CQtDeployer v1.6.2277 on Ubuntu 20, but it errors with "version GLIBC_2.34 not found".
Is Ubuntu 20 not supported anymore?

**Comment by EndrII** [comment]
The [deb](https://github.com/QuasarApp/CQtDeployer/releases) package requires >= Ubuntu 22.04.
For the older version, you may use the [snap](https://snapcraft.io/cqtdeployer) package. 
snap works greet on all Linux distributions and all version. 

Just do not forget sets all permissions for cqtdeploy after install
```bash
sudo snap install catdeployer
```

```
sudo snap connect cqtdeployer:process-control
sudo snap connect cqtdeployer:removable-media
sudo snap connect cqtdeployer:system-backup
```

**Comment by EndrII** [comment]
@Rbcum if your issue was solved, please close this issue.

**Comment by Rbcum** [comment]
Hi @EndrII 
Thanks for your quick reply, I tried the snap version on Github Actions with Ubuntu 20, but with no luck.
I've already granted the said permissons to cqtdeployer.

```
Verbose log: target deploy started!!
Verbose log: Available Targets: 
Info: copy :/home/runner/work/RepoMan/RepoMan/build/RepoMan
Verbose log: Target: /home/runner/work/RepoMan/RepoMan/DistributionKit/Application/bin//RepoMan
Error: LibInfo: path: '', name: '', qtPath: '', platform: '', dependencies: ''
Error: Internal error ocurred in smartMoveTargets (/mnt/storage/Workers/ubuntu20/cmake/LinuxCMakeBuilderQt6/QuasarApp/CQtDeployer/src/Deploy/src/configparser.cpp:1658).
Error: If you see this message please create a new issue about this problem on the official github page https://github.com/QuasarApp/CQtDeployer/issues/new/choose. 
Error: Fail to copy targets
Error: The CQtDeployer fail to deploy application.
```
Here is the complete log
[logs_21.zip](https://github.com/QuasarApp/CQtDeployer/files/10877416/logs_21.zip)

**Comment by EndrII** [comment]
> Hi @EndrII Thanks for your quick reply, I tried the snap version on Github Actions with Ubuntu 20, but with no luck. I've already granted the said permissions to cqtdeployer.
> 
> ```
> Verbose log: target deploy started!!
> Verbose log: Available Targets: 
> Info: copy :/home/runner/work/RepoMan/RepoMan/build/RepoMan
> Verbose log: Target: /home/runner/work/RepoMan/RepoMan/DistributionKit/Application/bin//RepoMan
> Error: LibInfo: path: '', name: '', qtPath: '', platform: '', dependencies: ''
> Error: Internal error ocurred in smartMoveTargets (/mnt/storage/Workers/ubuntu20/cmake/LinuxCMakeBuilderQt6/QuasarApp/CQtDeployer/src/Deploy/src/configparser.cpp:1658).
> Error: If you see this message please create a new issue about this problem on the official github page https://github.com/QuasarApp/CQtDeployer/issues/new/choose. 
> Error: Fail to copy targets
> Error: The CQtDeployer fail to deploy application.
> ```
> 
> Here is the complete log [logs_21.zip](https://github.com/QuasarApp/CQtDeployer/files/10877416/logs_21.zip)

Usualy so bug happents when cqtdeployer can't get full access to the target file. 
please check the your target for readable. 

```
/home/runner/work/RepoMan/RepoMan/build/RepoMan
```

**Comment by Rbcum** [comment]
OK I will check that later

**Comment by EndrII** [comment]
You close this issue, are you found solution and solve it ?
