### ISSUE TITLE
I can't seem to find qt6 library path in cqtdeployer.

### ISSUE THREAD

**Issue by hyun-shin** [QuasarApp/CQtDeployer#753]
I am developing with qtcreator Qt6.2. (OS linux mint)
I used to make a distribution version through cqtdepolyer, but I tried it again today and it didn't work. 
I want you to look at my problem.

libQt6Qml.so .6 exists in /usr/lib/x86_64-linux-gnu but cannot be found.

I don't understand if the command is wrong.

$cqtdeployer v
Info: Print info ...
CQtDeployer: 1.5.4.17 *** Binary Box ***
Qt: 5.15.2

I also have qt5.15 installed on my pc and it seems like cqtdeployer is looking for qt5.15 instead of qt6.2

"build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release" is build directory on QtCreator

"../qml-for-broadcasting" is my source direcotry

bcteam1@bcteam1-MINIPC-PN62:/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release$ cqtdeployer -bin SampleRadio -qmlDir ../qml-for-broadcasting -verbose 3
Verbose log: --- Working options table start ---
Verbose log: Option[bin]: SampleRadio
Verbose log: Option[qmlDir]: ../qml-for-broadcasting
Verbose log: Option[verbose]: 3
Verbose log: --- Working options table end ---
Verbose log: appDir = /home/bcteam1/CQtDeployer/1.5
Info: Deploy ...
Info: The targetDir option is not used. CQtDeployer will use default target dir :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit
Verbose log: The /home/bcteam1/CQtDeployer/1.5 path is ignored and not added to a search list!!
Verbose log:  is not a directory!! 
Verbose log: /snap/bin is not a directory!! 
Verbose log: /lib/systemd/system/hwclock.service is not a directory!! 
Verbose log: /lib/systemd/system/cryptdisks-early.service is not a directory!! 
Verbose log: /lib/systemd/system/lvm2.service is not a directory!! 
Verbose log: /lib/systemd/system/zfs-import.service is not a directory!! 
Verbose log: /lib/systemd/system/alsa-utils.service is not a directory!! 
Verbose log: /lib/systemd/system/rcS.service is not a directory!! 
Verbose log: /lib/systemd/system/x11-common.service is not a directory!! 
Verbose log: /lib/systemd/system/pulseaudio-enable-autospawn.service is not a directory!! 
Verbose log: /lib/systemd/system/cryptdisks.service is not a directory!! 
Verbose log: /lib/systemd/system/saned.service is not a directory!! 
Verbose log: /lib/systemd/system/rc.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/zfs-import.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/rc.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/saned.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/cryptdisks.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/hwclock.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/x11-common.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/alsa-utils.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/rcS.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/lvm2.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/cryptdisks-early.service is not a directory!! 
Verbose log: /usr/lib/systemd/system/pulseaudio-enable-autospawn.service is not a directory!! 
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/C:/windows/System32 is not a directory!! 
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/C:/windows/SysWOW64 is not a directory!! 
Verbose log:  not added in path mask because the path mask must be large 2 characters
Verbose log:  not added in file mask because the file mask must be large 2 characters
Verbose log: libpq is added as a filename mask
Verbose log: mysqlclient is added as a filename mask
Verbose log: libcrypto is added as a filename mask
Verbose log: libssl is added as a filename mask
Verbose log: libeay32 is added as a filename mask
Verbose log: ssleay32 is added as a filename mask
Verbose log: libicudata is added as a filename mask
Verbose log: libicui18n is added as a filename mask
Verbose log: libicuio is added as a filename mask
Verbose log: libicule is added as a filename mask
Verbose log: libiculx is added as a filename mask
Verbose log: libicutest is added as a filename mask
Verbose log: libicutu is added as a filename mask
Verbose log: libicuuc is added as a filename mask
Verbose log: libxcb-xinerama is added as a filename mask
Verbose log: libpng is added as a filename mask
Verbose log: libjpeg is added as a filename mask
Verbose log:  is not a directory!! 
Verbose log:  is not a directory!! 
Verbose log: target deploy started!!
Verbose log: Available Targets: 
Info: copy :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio
Verbose log: Target: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/bin//SampleRadio
Verbose log: extract lib :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/bin//SampleRadio
Verbose log: Get the recursive dependencies of /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/bin/SampleRadio
Verbose log: Cannot find the library for dependency libQt6Qml.so.6
Verbose log: Cannot find the library for dependency libGLX.so.0
Verbose log: Cannot find the library for dependency libgcc_s.so.1
Verbose log: Cannot find the library for dependency libc.so.6
Verbose log: Cannot find the library for dependency libQt6Core.so.6
Verbose log: Cannot find the library for dependency libstdc++.so.6
Verbose log: Cannot find the library for dependency libQt6Gui.so.6
Verbose log: Cannot find the library for dependency libOpenGL.so.0
Verbose log: extractQmlFromSource /mnt/ExtHDD/work/temp/qml-for-broadcasting
Warning: Failed to extract qml! The qt qml dir is not initialized!
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/build.ninja
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/cmake_install.cmake
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeCache.txt
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/3.22.1/CMakeCXXCompiler.cmake
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/3.22.1/CMakeDetermineCompilerABI_CXX.bin
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/3.22.1/CMakeSystem.cmake
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/3.22.1/CompilerIdCXX/a.out
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/3.22.1/CompilerIdCXX/CMakeCXXCompilerId.cpp
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/clean_additional.cmake
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/cmake.check_cache
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/CMakeOutput.log
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/d/36e6ee135bbe3b35491fd73c19bc84b1c79a060b49d36922d83a3952c745c67b.d
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/rules.ninja
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/AppManager.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/ipc/IPCInterfaceFactory.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/ipc/zmq/zmqImpl.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/main.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/SampleRadio_autogen/EWIEGA46WW/qrc_qt6_qml.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/SampleRadio_autogen/mocs_compilation.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/services/radio/command/RadioConcreteCommand.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/services/radio/invoker/RadioCommandInvoker.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/services/radio/RadioAppAdapter.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio.dir/services/radio/RadioAppService.cpp.o
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio_autogen.dir/AutogenInfo.json
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio_autogen.dir/AutogenUsed.txt
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio_autogen.dir/AutoRcc_qt6_qml_EWIEGA46WW_Info.json
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio_autogen.dir/AutoRcc_qt6_qml_EWIEGA46WW_Lock.lock
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio_autogen.dir/AutoRcc_qt6_qml_EWIEGA46WW_Used.txt
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/SampleRadio_autogen.dir/ParseCache.txt
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/CMakeFiles/TargetDirectories.txt
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/config.h
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/bin/SampleRadio ignored by filter/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/bin/SampleRadio ignored by rule /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/bin/qt.conf ignored by filter/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/bin/qt.conf ignored by rule /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/bin/SampleRadio ignored by filter/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/bin/SampleRadio ignored by rule /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/SampleRadio.sh ignored by filter/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/SampleRadio.sh ignored by rule /mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/qtcsettings.cmake
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio_autogen/AG2WTXC3SS/moc_RadioAppService.cpp
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio_autogen/AG2WTXC3SS/moc_RadioAppService.cpp.d
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio_autogen/deps
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio_autogen/EWIEGA46WW/qrc_qt6_qml.cpp
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio_autogen/moc_predefs.h
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio_autogen/mocs_compilation.cpp
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/SampleRadio_autogen/timestamp
Verbose log: Skip copy (by mask) :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/Testing/Temporary/LastTest.log
Verbose log: file with sufix ninja not supported!
Verbose log: file with sufix cmake not supported!
Verbose log: file with sufix txt not supported!
Verbose log: file with sufix cmake not supported!
Verbose log: file with sufix bin not supported!
Verbose log: file with sufix cmake not supported!
Verbose log: file with sufix out not supported!
Verbose log: file with sufix cpp not supported!
Verbose log: file with sufix cmake not supported!
Verbose log: file with sufix check_cache not supported!
Verbose log: file with sufix log not supported!
Verbose log: file with sufix d not supported!
Verbose log: file with sufix ninja not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: file with sufix cpp.o not supported!
Verbose log: extract lib :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/qml//CMakeFiles/SampleRadio_autogen.dir/AutogenInfo.json
Verbose log: file with sufix txt not supported!
Verbose log: extract lib :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/qml//CMakeFiles/SampleRadio_autogen.dir/AutoRcc_qt6_qml_EWIEGA46WW_Info.json
Verbose log: file with sufix lock not supported!
Verbose log: file with sufix txt not supported!
Verbose log: file with sufix txt not supported!
Verbose log: file with sufix txt not supported!
Verbose log: file with sufix h not supported!
Verbose log: file with sufix cmake not supported!
Verbose log: extract lib :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/qml//SampleRadio
Verbose log: file with sufix cpp not supported!
Verbose log: file with sufix cpp.d not supported!
Verbose log: extract lib :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/qml//SampleRadio_autogen/deps
Verbose log: file with sufix cpp not supported!
Verbose log: file with sufix h not supported!
Verbose log: file with sufix cpp not supported!
Verbose log: extract lib :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/qml//SampleRadio_autogen/timestamp
Verbose log: file with sufix log not supported!
Warning: Failed to copy standard Qt translations
Verbose log: Trying to deploy msvc
Verbose log: vcredist not defined
Verbose log: vcredist not found!
Verbose log: Failed to deploy msvc
Info: deploy done!
Verbose log: move : :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/bin/qt.conf
Verbose log: move : :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/bin/SampleRadio
Verbose log: move : :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/Application/SampleRadio.sh
Info: copy :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/tmp_data/Application/bin/qt.conf
Info: copy :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/tmp_data/Application/bin/SampleRadio
Info: copy :/mnt/ExtHDD/work/temp/build-qml-for-broadcasting-Desktop_Qt_6_2_4_GCC_64bit-Release/DistributionKit/tmp_data/Application/SampleRadio.sh

**Comment by hyun-shin** [comment]
sorry, resolved it.
cqtdeployer -bin Sample -qmlDir ../qml-for-broadcasting/ -qmake /Qt/6.2.4/gcc_64/bin/qmake

**Comment by EndrII** [comment]
@hyun-shin looks as you use old version old cqtdeployer 
I recommend use cqtdeployer 1.6 for last versions of the qt6.
