### ISSUE TITLE
How to create desktop shortcut

### ISSUE THREAD

**Issue by GuiguiPolytech** [QuasarApp/CQtDeployer#755]
Thanks to your app I can easily create a deb file. But I don't find the option to create .desktop in ~/.local/share/applications ?

How can I do it ?

**Comment by EndrII** [comment]
Hi. This is very hard for the deb packages. Because the deb package installs using root user. So the installation script does not know about your user directory and '~/' is /root 
so cqtdeployer add shortcut for application menu (/usr/share/applications), but this shortcut will be available after reboot only and not all OS systems support shortcuts on this path.

**Comment by GuiguiPolytech** [comment]
I'm currently on Ubuntu 20.04.

Here is my command :
cqtdeployer -bin ~/Documents/MyApp/bin/Exec deb -deployVersion 3.3.0 -description "Version with tooltips" -icon ~/Documents/MyApp/src/icon.png

So, there is no option to create a shortcut desktop with cqtdeployer ? Do you know a method to run a script automatically after the installation of deb file ?

Thanks

**Comment by EndrII** [comment]
The cqtdeployer tool automatically adds a script to create shortcuts

shortcut will be installed into 
**/usr/share/applications/**


Hm… I checked it on my Ubuntu, but shortcuts are not created ... 
looks as a bug. I try to fix it later

**Comment by GuiguiPolytech** [comment]
If I try with an older version of cqtdeployer, will there be the same bug? Or the bug is only on the new version?

**Comment by EndrII** [comment]
> 

I don't know. Maybe, but cqtdeployer 1.5 can work maximum with qt 6.2. 
> 6.3 - not tested...

**Comment by EndrII** [comment]
@GuiguiPolytech 
please try this [build](https://quasarapp.ddns.net:3031/QuasarApp/CQtDeployer/73c6255cef55c856532430e3d418e6ebd7163171/) of cqtdeployer with shortcut fixes. And leave your feedback here, please.

**Comment by GuiguiPolytech** [comment]
When I try the command (with your build) : cqtdeployer -bin ~/Documents/MyApp/bin/Exec deb -deployVersion 3.3.0 -description "Version with tooltips" -icon ~/Documents/MyApp/src/icon.png 

I get the following error : cqtdeployer -bin ~/Documents/MyApp/bin/Exec deb -deployVersion 3.3.0 -description "Version with tooltips" -icon ~/Documents/MyApp/src/daq_logo.png
/home/justin/CQtDeployer/1.6/bin/CQtDeployer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/justin/CQtDeployer/1.6/bin/ CQtDeployer)
/home/justin/CQtDeployer/1.6/bin/CQtDeployer: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/justin/CQtDeployer/1.6/lib/ libDeploy.so)
/home/justin/CQtDeployer/1.6/bin/CQtDeployer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/justin/CQtDeployer/1.6/lib/ libpe-parse.so)
/home/justin/CQtDeployer/1.6/bin/CQtDeployer: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/justin/CQtDeployer/1.6/lib/ libpe-parse.so)
/home/justin/CQtDeployer/1.6/bin/CQtDeployer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/justin/CQtDeployer/1.6/lib/ libzip.so)

**Comment by EndrII** [comment]
install snap package please 
snap install name.snap --dangerous

**Comment by GuiguiPolytech** [comment]
With snap package I have this error : 
Info: Deploy ...
Info: The targetDir option is not used. CQtDeployer will use default target dir :/home/justin/Documents/MyApp/DistributionKit
Error: The deployment target requires Qt libraries, but initialize of Qt directories is failed. Please use the qmake option to set a path to the qmake executable.
Info: If you are using qmake from the system repository, then you must use the classic version of CQtDeployer instead of the snap version. This is due to the fact that the snap version runs in an isolated container and has limited access to system utilities and the environment. For get the classic version of cqtdeployer use the cqtdeployer installer https://github.com/QuasarApp/CQtDeployer/releases
Error: Deploy failed!
Error: The CQtDeployer fail to read configuration.

And I'm currently on Ubuntu 20.04. So this package won't work ?

**Comment by EndrII** [comment]
Try to add permissions:
```
sudo snap connect cqtdeployer:process-control
sudo snap connect cqtdeployer:removable-media
sudo snap connect cqtdeployer:system-backup
```

**Comment by GuiguiPolytech** [comment]
It almost works, I don't have my logo on the shortcut (but there is a shortcut) !

**Comment by EndrII** [comment]
use the **-icon** option 
```
cqtdeployer  -icon my.png
```

**Comment by GuiguiPolytech** [comment]
It's already the case : cqtdeployer -bin ~/Documents/MyApp/bin/Exec deb -deployVersion 3.3.0 -description "Version with tooltips" -icon ~/Documents/MyApp/src/icon.png

And the name of the shortcut, it's the name of the script : Exec.sh

**Comment by EndrII** [comment]
> And the name of the shortcut, it's the name of the script : Exec.sh
Run script has the same name as your executable file.

**Comment by GuiguiPolytech** [comment]
I think there is always a mistake. Here is the result when I install the package generated by cqtdeployer.

![Screenshot from 2023-06-09 09-48-46](https://github.com/QuasarApp/CQtDeployer/assets/75668224/82e9176c-39ae-4a6f-b81e-0c926b51e2a0)

**Comment by EndrII** [comment]
Can you share your shortcut file ?

**Comment by GuiguiPolytech** [comment]
Here is the shortcut generated by cqtdeployer (/usr/share/applications) : 

[Desktop Entry]
Version=3.3.0
Encoding=UTF-8
Name=RebirXDAQ.sh
Type=Application
Icon=/opt/icons//opt/RebirXDAQ//RebirXDAQ.png
Terminal=false
Exec=/opt/RebirXDAQ//RebirXDAQ.sh

**Comment by EndrII** [comment]
this icon is exists ? 
```
/opt/icons//opt/RebirXDAQ//RebirXDAQ.png
```

For change name, try -name option

**Comment by GuiguiPolytech** [comment]
There is icon at /opt/RebirXDAQ/icons/RebirXDAQ.png.

**Comment by GuiguiPolytech** [comment]
-name RebirXDAQ do not change. It's always RebirxXDAQ.sh

**Comment by GuiguiPolytech** [comment]
The problem comes from the generated desktop file. Here is the correction of it: 
[Desktop Entry]
Version=3.3.0
Encoding=UTF-8
Name=RebirXDAQ
Type=Application
Icon=/opt/RebirXDAQ/icons/RebirXDAQ.png
terminal=false
Exec=/opt/RebirXDAQ/RebirXDAQ.sh

Anyway, thank you for being so responsive.

**Comment by EndrII** [comment]
@GuiguiPolytech check please [this](https://quasarapp.ddns.net:3031/QuasarApp/CQtDeployer/d35f0c339b648bf665a6be22a29e1ec984534d35/) version 
install the snap package and add all permissions again.

**Comment by GuiguiPolytech** [comment]
Thanks ! Everything works fine !

**Comment by EndrII** [comment]
Okay. This fixes will be released on the next release.
I will close this issue after merge.
