### ISSUE TITLE
Create .run from distribution kit folder

### ISSUE THREAD

**Issue by AhmedAredah** [QuasarApp/CQtDeployer#761]
**Is your feature request related to a problem? Please describe.**
There is no way that I can copy a folder to the distribution kit or to a specific directory inside. 

**Describe the solution you'd like**
I tried to create the distribution kit myself but the tool does not give an option to create the .run file from the distribution kit.

**Comment by EndrII** [comment]
Hi. Can you show me your console command of cqtdeployer tool ?

For creating a run executable, you should use the **qif** option. 
if you use the cqtdeployer from the deb package, you must [install ](https://doc.qt.io/qtinstallerframework/index.html)the qt install framework and register it in your path variable.


For the snap version of cqtdeployer

```bash
cqtdeployr ... qif
```

For the deb version of cqtdeployer with external qt installer framework 

```bash
cqtdeployer ... -qif /path/to/your/binarycreator/executable
```

**Comment by EndrII** [comment]
i close this issue. Because it is inactive
