### ISSUE TITLE
Deploy of projec on Qt 5.12.11 does not include libQt5Concurrent.so.5

### ISSUE THREAD

**Issue by kasonyin** [QuasarApp/CQtDeployer#762]
Hi,
I'm on Ubuntu 16.04. I have a Qt project that use CMake. I package my project using cqtdeployer,
the library libQt5Concurrent.so.5 was reported as not found when I ran it, however, I checked the dependencies with ldd and found that my application requires this library.

![image](https://github.com/QuasarApp/CQtDeployer/assets/14540836/ff482d2d-296c-4dc3-9dec-98b5cbff19e5)

![image](https://github.com/QuasarApp/CQtDeployer/assets/14540836/19e27e16-a2f6-459b-9871-eb2a0813eb7d)

How can I include it ?

Thanks

**Comment by EndrII** [comment]
@kasonyin show me your verbose log of cqtdeployer. Run the deploy command with -verbose 3 

```
cqtdeployer ... -verbose 3 
```

**Comment by kasonyin** [comment]
> @kasonyin show me your verbose log of cqtdeployer. Run the deploy command with -verbose 3
> 
> ```
> cqtdeployer ... -verbose 3 
> ```

Thanks for your answer.

I found the problem. The reason is that I have some custom libraries in my project, and in one of them libQt5Concurrent.so is referenced, but I didn't specify the path to my libraries when I used CQtDeploy (because I found out that if I specified the custom library path with -libDir, I couldn't find the qt libraries correctly)

**Comment by EndrII** [comment]
The libDir option works as a PATH variable, so all paths that you will add into libDir option mark all DLL and SO files as allowed for deploy. And if you have dependencies to some library from the libDir directory, then this library will be copied into your distribution. 

If you want to force copy, one library but not known where is it, you can use the extraDepends option. 

### note 
the extraDepends option still not available in the last version catdeployer. I will release this option on the next release.

**Comment by kasonyin** [comment]
Okay, got it. Thanks a lot for your patience.

**Comment by EndrII** [comment]
@kasonyin can I close this issue ?

**Comment by kasonyin** [comment]
> @kasonyin can I close this issue ?

Of course, thanks again for your answer!
