### ISSUE TITLE
How to uninstall CQtDeployer in linux?

### ISSUE THREAD

**Issue by BingoZha** [QuasarApp/CQtDeployer#774]

**Comment by EndrII** [comment]
CQtDeployer distribute to 3 packages types.
* snap 
* deb
* classic installer

So for delete appcation from your computer you need to do:

### snap 
```
sudo snap remove cqtdeployer 
```
or you can press button remove on your snap-store. 

### deb
```
sudo apt remove cqtdeployer
```

### installer

* go to application folder (usualy it is /home/user/CQtDeployer)
* ru the **CQtDeployerTool** programm
* choose remove all option.
![image](https://github.com/QuasarApp/CQtDeployer/assets/12465465/3f2111ee-ff1d-4554-991d-468309b02dab)

**Comment by EndrII** [comment]
@BingoZha  close this issue if it was solved to you.
