### ISSUE TITLE
Cant run deployed sh :"/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found"

### ISSUE THREAD

**Issue by BingoZha** [QuasarApp/CQtDeployer#775]
I comiled the project in Unbuntu 22.04 and use CQtDeployer to deploy.It can run perfectly in Unbuntu.
Then I move the deployed folder to centOS 7.9, it reports some error:
/root/Deployer/ServerTest/DistributionKit/bin/ServerTest: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/Deployer/ServerTest/DistributionKit/bin/ServerTest)
/root/Deployer/ServerTest/DistributionKit/bin/ServerTest: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/Deployer/ServerTest/DistributionKit/bin/ServerTest)
/root/Deployer/ServerTest/DistributionKit/bin/ServerTest: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/Deployer/ServerTest/DistributionKit/bin/ServerTest)
How to fix it?

**Comment by EndrII** [comment]
This is libc issue. So just build and deploy your distribution on oldest OS, 
The centOS 7.9 have libc [version](https://centos.pkgs.org/7/centos-x86_64/glibc-2.17-317.el7.x86_64.rpm.html) 2.17 - this is supper too old... so and unfixable

For example, Ubuntu 16.04 has libc version 2.23

So you should build your app only on centos 7.9

**Comment by BingoZha** [comment]
Thank you.
