### ISSUE TITLE
How to install CQtDeployer in docker ubuntu 20

### ISSUE THREAD

**Issue by sonphambk** [QuasarApp/CQtDeployer#776]
Hi .
Thank you for your work
I want to install CQtDeployer in docker ubuntu 20 but it does not work. Could you help me about this?

**Comment by EndrII** [comment]
Hi,  @sonphambk thanks.
To install cqtdeployer on the OS that has a libc version less than 2.35 use the **snap** version. (Ubuntu 20.04 have only 2.31)
See our [docs](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_Build_and_Install.html) - Snap section.

**Comment by sonphambk** [comment]
Thanks for your respone.
I tried to install by using snap but it has an issue
![image](https://github.com/QuasarApp/CQtDeployer/assets/48971289/5e09551c-b8cb-4b85-9aa2-fdf12bce536b)

**Comment by sonphambk** [comment]
I want to integrate CQtDeployer into bitbucket pipeline to deploy my app when release. So I try to install in docker before.

**Comment by sonphambk** [comment]
I just found a solution to install cqtdeployer in docker ubuntu20.
- Install cqtdeployer from source in local machine (ubuntu20) and make deploy to create .deb file
- Copy .deb file from local machine to docker container and install it.

**Comment by EndrII** [comment]
I will close this issue 

> I just found a solution to install cqtdeployer in docker ubuntu20.
> 
>     * Install cqtdeployer from source in local machine (ubuntu20) and make deploy to create .deb file
> 
>     * Copy .deb file from local machine to docker container and install it.
