### ISSUE TITLE
libxcb-xinerama not found

### ISSUE THREAD

**Issue by GoldSnake2100** [QuasarApp/CQtDeployer#779]
I built my app installer on ubuntu220.0.4, and it works on the machine. But I run the installer on other machine runs ubuntu 22.0.4, the installer does not work.
This is the log when I run the installer.

`./InstallerCOMINT.run: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory`

I tried to add extraLibs option, but it results same.

This is deploy command I used.

`cqtdeployer -bin COMINT -qmake /home/hkc/Qt/6.5.2/gcc_64/bin/qmake -qmlDir /home/hkc/Comint/COMINT/resource/qml -extraLibs libxcb-xinerama qif`

**Comment by EndrII** [comment]
@GoldSnake2100 can you send me verbose log of cqtdeployer tool ? 
just add -verbose 3 to your deploy command

**Comment by GoldSnake2100** [comment]
Here is attacted the verbose log file.
[verbose-log.txt](https://github.com/QuasarApp/CQtDeployer/files/13029792/verbose-log.txt)

**Comment by EndrII** [comment]
Hm, libxcb-xinerama.so.0 is dependency of the qt plugins, so just mark this lib as a depends on your executable.
Use the new **extraDepends** option 

```
-extraDepends libxcb-xinerama.so.0
```

**Comment by GoldSnake2100** [comment]
Thanks, I just tried to use the extraDepends option, but the result is same.
This is the deploy command and verbose log file
[verbose-log.txt](https://github.com/QuasarApp/CQtDeployer/files/13030244/verbose-log.txt)

**Comment by GoldSnake2100** [comment]
The problem is just not running .run installer file, I am not sure the libxcb-xinerama lib is related with my application itself.
When I manually install libxcb-xinerama library to target machine, the installer just run and my application also works.
but I can't tell users to install the lib manually before use the installer.

**Comment by EndrII** [comment]
@GoldSnake2100 we should wait for solve this [issue](https://bugreports.qt.io/browse/QTIFW-2500) by Qt Installer team

**Comment by EndrII** [comment]
i close this issue, because it is qt installer framework issue.
