### ISSUE TITLE
The link in docs shows wrong page that doesn't exist

### ISSUE THREAD

**Issue by NLLK** [QuasarApp/CQtDeployer#784]
**Describe the bug**
The link in docs shows wrong page that doesn't exist

**To Reproduce**
1. Go to [docs page](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_ru_CustomScripts.html) or [eng version](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_en_CustomScripts.html)
2. Click on the link at the bottom of the page
3. See it opens the [wrong link](https://github.com/QuasarApp/CQtDeployer/tree/main/Deploy/ScriptsTemplates)

**Expected behavior**
It opens the right link, [probably this link](https://github.com/QuasarApp/CQtDeployer/tree/main/src/Deploy/src/ScriptsTemplates)

**Comment by EndrII** [comment]
> **Expected behavior** It opens the right link, [probably this link](https://github.com/QuasarApp/CQtDeployer/tree/main/src/Deploy/src/ScriptsTemplates)

Yes, current link is deprecated. You found a right link. Please make a pull request with a new link on documentation.
Use absolute link.

Thank you

**Comment by NLLK** [comment]
I have created a separate pull request for this #785
