### ISSUE TITLE
Cmake support

### ISSUE THREAD

**Issue by SergeyDG29** [QuasarApp/CQtDeployer#787]
Good afternoon, please clarify does CQtDeployer support building only qmake or does it work with cmake?
When building on cmake, I did not notice any problems in Qt 6.5.

> cqtdeployer -bin ASAMEventLog -qmake /home/sergey/QtNew/6.5.2/gcc_64/bin/qmake qif -qifstyle QuasarDark -libDir /QLibrary -extraLibs libxcb -icon /home/sergey/QtProject/build-ASAMEventLog-Desktop_Qt_6_5_2_GCC_64bit-Release/LogoASAM.ico

**Comment by EndrII** [comment]
The qmake options just using to get information about qt paths for specific qt locations. Qt still not provide this information in main cmake file. 

Yes, it will be works correctly for all versions of Qt (include latest Qt that contains qmake only as wrapper of cmake). 
This is just a historical syntax. It might make sense to rename this option in the future. For example, **QtRootDir** or something else...

**Comment by SergeyDG29** [comment]
Да это было хорошей мыслью и не вводило в заблуждение

**Comment by SergeyDG29** [comment]
Yes, that was a good idea and not misleading

**Comment by EndrII** [comment]
@SergeyDG29 see #788
