### ISSUE TITLE
Copy extraData to multiple directories

### ISSUE THREAD

**Issue by hirseboy** [QuasarApp/CQtDeployer#798]
Sorry, I did not fully understand your documentation, but is it possible to copy extraData to multiple directories?

**Comment by EndrII** [comment]
Hi, it's simple. 
just prepare your extra data dirs. 
For example 

myDir/with/extra1/
myDir/with/extra2


Each dirs should be contained own subdirectory that should be to contain in your distribution. 
and just add your dirs with extra data to deploy. After this, override the output directory using a extraDataOut option, to a distribution root dir..
```
cqtdeployer -extraDir "myDir/with/extra1/,myDir/with/extra2" -extraDataOut "/"
```

**Comment by EndrII** [comment]
here is my example 
[extraDataMultiDirExample.zip](https://github.com/QuasarApp/CQtDeployer/files/14433544/extraDataMultiDirExample.zip)

**Comment by EndrII** [comment]
i will close this issue,
