### ISSUE TITLE
QIF banner/logo on cross-compiled app (Linux->Windows)

### ISSUE THREAD

**Issue by higaski** [QuasarApp/CQtDeployer#799]
I'm having troubles adding a banner (and or a logo) to an installer created by the binary creator. Creating the installer itself works fine. I have this custom CMake command which invokes the CQtDeyployer executable and passes things on to the binarycreator through Wine.

```cmake
add_custom_command(
  TARGET MSim
  POST_BUILD
  COMMAND
    ${CQTDEPLOYER_EXECUTABLE} 
    force-clear 
    noTranslations 
    qif 
    -bin $<TARGET_FILE:MSim> 
    -qmake ${QMAKE_EXECUTABLE} 
    -libDir ${LIB_DIRS} 
    -recursiveDepth 2 
    -targetDir ${CMAKE_BINARY_DIR}/deploy 
    -verbose 3 
    -platform win_x86_64 
    -icon ${CMAKE_CURRENT_SOURCE_DIR}/src/MSim.ico 
    -qifBanner ${CMAKE_CURRENT_SOURCE_DIR}/data/images/ZIMO_small.png # Adding banner
    -qifLogo ${CMAKE_CURRENT_SOURCE_DIR}/data/images/logo.png # Adding logo
    -qifOut MSim-${PROJECT_VERSION}-x86_64 
    -qifConfig ${CMAKE_BINARY_DIR}/config.xml 
    -binarycreator "${WINE_EXECUTABLE} ${BINARYCREATOR_WINDOWS_EXECUTABLE}")
```

The output of this command also suggests that the specified files have been found
```sh
Info: Use a default installer style
Info: copy :/home/vinci/Develop/VSCode/MSim/data/images/ZIMO_small.png
Info: copy :/home/vinci/Develop/VSCode/MSim/data/images/logo.png
```
[log.txt](https://github.com/QuasarApp/CQtDeployer/files/14433324/log.txt)

When running the installer on Windows however neither banner nor logo show up
![win](https://github.com/QuasarApp/CQtDeployer/assets/13762516/8a732787-c1fd-42ef-a4cc-08adbc339392)

**Comment by EndrII** [comment]
Hi, give me more time to answer please, I will check this issue to evening.

**Comment by higaski** [comment]
This is an absolute luxury problem, please take as much time as you want.

**Comment by EndrII** [comment]
hmm probably its windows only issue. Because on the linux version all works is fine. I need more time to solve it. 
![image](https://github.com/QuasarApp/CQtDeployer/assets/12465465/55c05b2e-8b49-4140-b678-523827b3473a)

**Comment by EndrII** [comment]
i finish checked your issue on the both platforms (windows/linux), all works fine. 
probably trouble in the binarycreator executable. What version of qifw do you use ?
Just run your installer with version option 

```
InstallerApplication.exe -verison
```

**Comment by higaski** [comment]
I get the feeling that I'm doing something wrong?
Are there any size or path restrictions to the banner and logo files?

I've now tried to add just a banner (even the one from the CQtDeployer repo... just to be sure) on my host linux machine with the following two releases

Using CQtDeployer 1.5.4.17 (Linux only):
```sh
IFW Version: 4.4.0, built with Qt 5.15.2.
Build date: Jun  7 2022
Installer Framework SHA1: e8025cdfe0d85c8ac9199784e95d88bf001a8a99
Libarchive version: libarchive 3.6.1 zlib/1.2.7 liblzma/5.2.2 bz2lib/1.0.8
```

Using CQtDeployer 1.6.2323 (Linux only):
```sh
IFW Version: 4.6.1, built with Qt 5.15.2.
Build date: Aug 23 2023
Installer Framework SHA1: e99494a7abfd8509decd2ab46f84bc9e5bd5794f
Libarchive version: libarchive 3.6.2 zlib/1.2.11 (Qt) liblzma/5.2.2 bz2lib/1.0.8
```

One once compiling on my host for windows and then using CQtDeployer 1.6.2345 (so Linux and Windows binaries)
```sh
IFW Version: 4.7.0, built with Qt 6.6.0.
Build date: Feb 15 2024
Installer Framework SHA1: fad83b7a8ba6a9e3179236d11bba0ceb9b3de5b4
Libarchive version: libarchive 3.7.1 zlib/1.2.12 liblzma/5.2.5 bz2lib/1.0.8
```

**Comment by EndrII** [comment]
Yes, I found a mistake in your config. 
you use custom configuration of qt installer framework instead of default that contains rules for logo and banner.

Just remove the     **-qifConfig ${CMAKE_BINARY_DIR}/config.xml**  line  

Or take cqtdeployer default config and modify it.  Available [here](https://github.com/QuasarApp/CQtDeployer/blob/main/src/Deploy/src/Distributions/Templates/qif/config%20custom%20designe/config.xml).

**Comment by higaski** [comment]
Thank you very much, I didn't realize that those options need to be added to the .xml

**Comment by EndrII** [comment]
> Thank you very much, I didn't realize that those options need to be added to the .xml

Yes, it's qifw feature 
see qifw [documentation](https://doc.qt.io/qtinstallerframework/ifw-globalconfig.html) about config file.

**Comment by higaski** [comment]
I'm sorry but I've to reopen this issue. I can't get a custom config.xml file to show me a banner.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Installer>
  <Name>${APPLICATION_NAME}</Name>
  <Version>${PROJECT_VERSION}</Version>
  <Title>${APPLICATION_NAME} Installer</Title>
  <Publisher>${ORGANISATION_NAME}-Elektronik</Publisher>
  <Banner>../data/images/banner.png</Banner>
  <StartMenuDir>${ORGANISATION_NAME}/${APPLICATION_NAME}</StartMenuDir>
  <TargetDir>${INSTALLER_APP_DIR}/${ORGANISATION_NAME}/${APPLICATION_NAME}</TargetDir>
</Installer>
```

The verbose output claims the banner has been found
```
Info: [23015] Read dom element: <Banner>../data/images/banner.png</Banner>.

Info: [23015] Copying associated "Banner" file "Z:/home/vinci/Develop/VSCode/ZIMO-Elektronik/MSim/data/images/banner.png"

Info: [23016] done.
```
