### ISSUE TITLE
error while loading shared libraries: libb2.so.1

### ISSUE THREAD

**Issue by avttrue** [QuasarApp/CQtDeployer#800]
build system: Ubuntu (KDE Neon, Wayland)
clear test system: Ubuntu (KDE Neon, x11), VirtualBox

I have created two packages:
`cqtdeployer -bin myApp deploySystem `
&
`cqtdeployer -bin myApp`

In both cases, when running on a clean system, I get the same error:
`error while loading shared libraries: libb2.so.1: cannot open shared object file: No such file or directory`
List of libraries in packages:
[1.txt](https://github.com/QuasarApp/CQtDeployer/files/14477621/1.txt)

**Comment by EndrII** [comment]
Hi, 
can you show me **ldd** output of your main executable, and your own built libraries (if you have) with -verbose option ?

**Comment by avttrue** [comment]
verbose log added
[ verboselog.txt](https://github.com/QuasarApp/CQtDeployer/files/14478946/verboselog.txt)

**Comment by EndrII** [comment]
Please do not use systemLibs option. It is not save. 



Just mark your lib as approved 

```
cqtdeployer -extraLibs libb2
```

**Comment by avttrue** [comment]
Thanks, it helped. By the way, I did not use additional options like "systemLibs".
