### ISSUE TITLE
platform integration problem

### ISSUE THREAD

**Issue by avttrue** [QuasarApp/CQtDeployer#803]
Build system: Linux KDE Neon, wayland
Test system: Linux KDE Neon, wayland, X11

`cqtdeployer -bin MyApp -extraLibs "libb2,libxcb-cursor" -enablePlugins multimedia`

When executing a `MyApp.sh` file from `DistributionKit` directory, a number of error messages are displayed in the console. The main problem I noticed is the **incorrect** functionality of file dialogs and some deviations in GUI styles.

Including string `export QT_QPA_PLATFORM=xcb` in `MyApp.sh` file eliminates the "qt.qpa.wayland:..." messages but does not solve the problem in file dialogs.

Error messages:

> qt.qpa.wayland: Failed to load client buffer integration: "wayland-egl"
> qt.qpa.wayland: Available client buffer integrations: QList()
> ...
> kf.windowsystem: Could not find any platform plugin
> ...
> kf.kio.core: couldn't create worker: "Неизвестный протокол «file»."
> kf.kio.core: couldn't create worker: "Неизвестный протокол «file»."

[lddlog.txt](https://github.com/QuasarApp/CQtDeployer/files/14539614/lddlog.txt)
[verboselog.txt](https://github.com/QuasarApp/CQtDeployer/files/14539615/verboselog.txt)
[DistributionKit.txt](https://github.com/QuasarApp/CQtDeployer/files/14539766/DistributionKit.txt)

**Comment by EndrII** [comment]
hm, looks as bug o cqtdeployer. 
because your distribution missed 2 Wayland plugins.

**Comment by EndrII** [comment]
@avttrue can you try force to enable missed plugins for test ? 
``` bash
-enablePlugins "multimedia,wayland-decoration-client,wayland-graphics-integration-client"
```

**Comment by avttrue** [comment]
> @avttrue can you try force to enable missed plugins for test ?
> 
> ```shell
> -enablePlugins "multimedia,wayland-decoration-client,wayland-graphics-integration-client"
> ```

The message no longer appears

> qt.qpa.wayland: ...

But these messages remained, and the problems associated with them.
The first access to the menu:

> kf.windowsystem: Could not find any platform plugin

Calling the file dialog:

> kf.kio.core: couldn't create worker: "Неизвестный протокол «file»."
> kf.kio.core: couldn't create worker: "Неизвестный протокол «file»."

As for the problems I had in mind. Here's what's expected:

![Снимок экрана_20240309_124223](https://github.com/QuasarApp/CQtDeployer/assets/5796132/e4bb72c1-e7f9-43de-9f76-d8e420ab9374)
![Снимок экрана_20240309_124328](https://github.com/QuasarApp/CQtDeployer/assets/5796132/fd1e7815-619b-439f-8571-ac909cdac1bf)
---
And here is how it is displayed when running through the DistributionKit:

![Снимок экрана_20240309_124427](https://github.com/QuasarApp/CQtDeployer/assets/5796132/0241dda8-c283-4609-b4c0-e785a9b870b5)
![Снимок экрана_20240309_124537](https://github.com/QuasarApp/CQtDeployer/assets/5796132/14da9edd-3d60-4bd8-a6d1-18d18f9e5abe)


[DistributionKit.txt](https://github.com/QuasarApp/CQtDeployer/files/14545888/DistributionKit.txt)

**Comment by avttrue** [comment]
Here is a test project: [test](https://disk.yandex.ru/d/YxHyrLFSpCHK9g)

**Comment by EndrII** [comment]
Add please the "wayland-graphics-integration-server" plugin too

```
-enablePlugins "multimedia,wayland-decoration-client,wayland-graphics-integration-client,wayland-graphics-integration-server"
```

**Comment by avttrue** [comment]
> Add please the "wayland-graphics-integration-server" plugin too
> 
> ```
> -enablePlugins "multimedia,wayland-decoration-client,wayland-graphics-integration-client,wayland-graphics-integration-server"
> ```

No changes:
`cqtdeployer -bin test_TextEdit -extraLibs "libb2,libxcb-cursor" -enablePlugins "multimedia,wayland-decoration-client,wayland-graphics-integration-client,wayland-graphics-integration-server" -verbose 3 >&verboselog.txt`

[dirlog.txt](https://github.com/QuasarApp/CQtDeployer/files/14546228/dirlog.txt)
[verboselog.txt](https://github.com/QuasarApp/CQtDeployer/files/14546229/verboselog.txt)

---

**Comment by EndrII** [comment]
Unfortunately, I don't know what exactly is missing from your distribution. If you manage to figure it out—either through the usual method of trying out plugins or Qt libraries—please describe it in this post, and I will assign this task to you.

**Comment by avttrue** [comment]
I think I found the problematic plugins. Without these plugins, that problems do not appear. Need to test it more.  Perhaps these plugins are missing something additionally.

> plugins/1$ dir -R -h
> .:
> platformthemes  styles  wayland-decoration-client
> 
> ./platformthemes:
> KDEPlasmaPlatformTheme6.so  libqgtk3.so  libqxdgdesktopportal.so
> 
> ./styles:
> breeze6.so  oxygen6.so
> 
> ./wayland-decoration-client:
> libbradient.so

**Comment by avttrue** [comment]
1. Problematic plugins: `platformthemes, styles, wayland-decoration-client`
2. The `wayland-graphics-integration-server` plugin is probably not needed. The absence of this plugin does not affect anything.
3. The message displayed on X11 `Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory`, but I don't have such a library. I don't know if this library is necessary.
4. The final command for my distribution kit at this moment:
`cqtdeployer -bin MyApp -extraLibs "libb2,libxcb-cursor,libvdpau_va_gl" -enablePlugins "multimedia,wayland-graphics-integration-client,wayland-graphics-integration-server" -disablePlugins "platformthemes,styles,wayland-decoration-client"`
5. The main problem was that at some stage an errors occurred when accessing plugins responsible for GUI styles and themes.

I will still test on other systems, but at this moment the distribution kit is working.

**Comment by EndrII** [comment]
About the multimedia, wayland-graphics-integration-client, 
plugins. At current time, these plugins deployed automatically.
So you can skip it.  

I will close this issue. Because issues is founded inner Qt libraries/ and all cqtdeployer issues is fixed.
