### ISSUE TITLE
Implementation of copying multiple directories

### ISSUE THREAD

**Issue by AnSMru** [QuasarApp/CQtDeployer#807]
Мне необходимо выполнить настройку подобную этой:
"extraData": [
    "c:\\gstreamer\\1.0\\mingw_x86_64\\bin\\*.dll"
    ],
"extraDataOut": "lib/bin",
"extraData": [
    "c:\\gstreamer\\1.0\\mingw_x86_64\\lib\\*.dll"
    ],
"extraDataOut": "lib/lib",

То есть скопировать файлы с учетом структуры, но воспринимается только последний параметр. Хотелось бы видеть такую возможность.

**Comment by EndrII** [comment]
Just use universal root Dir for your extra data. 

``` json
"extraData": [
"c:/gstreamer/1.0/mingw_x86_64/"
],
"extraDataOut": "lib",
"ignore": [
     "c:/gstreamer/1.0/mingw_x86_64/noneededPath1",
     "c:/gstreamer/1.0/mingw_x86_64/noneededPath2",
     ".noneededExtensions"
]
```


Note : Please use english language to asking or discuss, The russian language can be Incomprehensible to most users.

**Comment by AnSMru** [comment]
That is, to do it by the exclusion method, and not by the necessary list?

**Comment by EndrII** [comment]
> That is, to do it by the exclusion method, and not by the necessary list? But I only need the dll, and in the directory c:/gstreamer/1.0/mingw_x86_64 / more than 4000 files. All I need is ./bin/_.dll (200 files) and ./lib/gstreamer-1.0/_.dll (194 files)

Yes, just fill an ignore list to your prefix. 
at now, it is a single way to solve your issue.
