### ISSUE TITLE
Install custom plugin libqsqlmysql on Linix with application

### ISSUE THREAD

**Issue by STILSIK99** [QuasarApp/CQtDeployer#815]
I build custom plugin (libqsqlmysql.so) for my application guided by same instruction:
"https://stackoverflow.com/questions/6483523/qt-how-to-getcompile-mysql-driver".

When i finished my application, i need build deb package for that.
There are many dependencies among which mysql plugin, i don't understand how install it.

**Comment by EndrII** [comment]
@STILSIK99 do you want to prepare deb package for plugin only (and create dependency to app) or for all your App include this plugin ?

**Comment by STILSIK99** [comment]
@EndrII , I want to prepare deb package of my app, that use plugin qtsqlmysql.

**Comment by EndrII** [comment]
Okay its easy 
just run **cqtdeployer** with two option **deb and -extraPlugin**

``` bash
cqtdeployer ... -extraPlugin path/to/plugin/bin/dir deb
```

or 

``` bash
cqtdeployer ... -extraPlugin path/to/libqsqlmysql.so deb
```

So where ... - is other required options like **-bin** or **-qmake** 

The cqtdeployer prepare an independent Debian package for your application.

**Comment by STILSIK99** [comment]
Thanks, next step.
I have some truble with addition my DEBIAN configurations.
CQtDeployer print "Use custom template", but metadata of deb package include standard template (not my).

**Comment by STILSIK99** [comment]
I suppose my configuration for build have some errors, if check it by lintian tool.
So CQtDeployer don't want to use my configuration. But no more infomation about it in output.

**Comment by EndrII** [comment]
Yes its documentation mistake, the help for deb option have bad documentation, so I updated it. @STILSIK99 please check new version and leave your feedback.

**Comment by EndrII** [comment]
@STILSIK99  therefore you may learn more about creating deb using cqtdeployer tool [here](https://quasarapp.ddns.net:3031/docs/QuasarApp/CQtDeployer/latest/md_md_2en_2DEB.html)

.
