### ISSUE TITLE
Deploy to windows from Linux 

### ISSUE THREAD

**Issue by Mosazghi** [QuasarApp/CQtDeployer#819]
I have successfully deployed on linux, but now i want to deploy my app to windows from linux as well. How to do that? I don't find any documentation regarding this. 

command i used to deploy to linux 
```
▶ cqtdeployer -bin my_t -libDir ../../install/lib qif -qmake /home/mosa/Qt/6.7.2/gcc_64/bin/qmake 
```

**Comment by EndrII** [comment]
For windows, it will be same, but you should set path to windows libs and qamke 
```
cqtdeployer -bin myexecutable.exe -qmake ~/crossbuildet-Qt/5.15.0/min_gw/bin/qmake.exe 
```
but cqtdeployer does not have an executable of qt installer framework 
so you need to install a wine and override path to windows prebuild qt installer framework 

see my old answer https://github.com/QuasarApp/CQtDeployer/issues/193#issuecomment-1288940111

**Comment by Mosazghi** [comment]
> For windows, it will be same, but you should set path to windows libs and qamke
> 
> ```
> cqtdeployer -bin myexecutable.exe -qmake ~/crossbuildet-Qt/5.15.0/min_gw/bin/qmake.exe 
> ```
> 
> but cqtdeployer does not have an executable of qt installer framework so you need to install a wine and override path to windows prebuild qt installer framework
> 
> see my old answer [#193 (comment)](https://github.com/QuasarApp/CQtDeployer/issues/193#issuecomment-1288940111)

so i have cannot deploy a windows instance of the app directly from ubuntu? 
if yes, then i'd have to install Qt on windows and deploy from there instead, right?

**Comment by EndrII** [comment]
@Mosazghi No, it should works on Ubuntu, but you must prepare windows build using cross-platform toolkit and cross-platform build of qt.

After successful build, you must install "qt installer framework" for windows platform and invoke cqtdeployer 

With next arguments : 

```
cqtedployer -bin winApp.exe -qmake path/to/qmake qif -binarycreator "wine path/to/binarycreator.exe"
```

**Comment by Mosazghi** [comment]
Is there some for of a tutorial i can refer to? I quite didn't get your answer. 
> windows build using cross-platform toolkit and cross-platform build of qt
How?

Also why use wine? binarycreator is?

**Comment by EndrII** [comment]
> Is there some for of a tutorial i can refer to? I quite didn't get your answer.
> 
> > windows build using cross-platform toolkit and cross-platform build of qt
> > How?
> 
> Also why use wine? binarycreator is?

Oh, i think its first cross-build/deploy experience for you ... I can't found real understandably article on internet. So I will try to prepare it for you, but I need more time. And I need your help. 

## So our plan:
1. I prepare article for by cross development from Linux to windows (include cross deploy with create distribution with installer) 
2. you will try to reproduce it step by step. And leave feedback for each article steps. 
3. I will fix mistakes on my article 
4. you will leave general feedback about my guideline. 

Please let me know, can I start to work on the article ?

**Comment by Mosazghi** [comment]
> Please let me know, if can I start to work on the article.

Yes, you can. And I am glad i can help. 

This is indeed my first time cross-deploying. 

Just tell me how i can assist you (here or on some other platform? and stuff like that).

**Comment by EndrII** [comment]
> > Please let me know, if can I start to work on the article.
> 
> Yes, you can. And I am glad i can help.
> 
> This is indeed my first time cross-deploying.
> 
> Just tell me how i can assist you (here or on some other platform? and stuff like that).

okay, i reopen the #193  issue.

**Comment by EndrII** [comment]
@Mosazghi please see this article and let me know your feedback. If you have any questions, please ask on GitHub gists
