### ISSUE TITLE
Please add support modify startup script

### ISSUE THREAD

**Issue by kasonyin** [QuasarApp/CQtDeployer#828]
My software runs on an embedded platform where the Qt libraries have already been pre-deployed in the `/usr/lib`. I would like to modify the startup script to include environment variables such as QT_PLUGIN_PATH and QT_QPA_PLATFORM_PLUGIN_PATH, or allow me to add some environment variables in the startup script, like this:

```
#!/bin/sh

# This is default bat run script of The CQtDeployer project.
# This file contains key word that will replaced after deploy project.
#
# ####################################################################
#
# All variables has the CQT_ prefix
# BIN_PATH - are releative path to executable files of a deployed distribution.
# LIB_PATH - are releative path to libraryes of a deployed distribution.
# QML_PATH - are releative path to qml libraryes of a deployed distribution.
# PLUGIN_PATH - are releative path to qt plugins of a deployed distribution.
# BIN_PATH - are releative path to targets of a deployed distribution.

# SYSTEM_LIB_PATH - are releative path to system libraryes of a deployed distribution.
# BASE_NAME - are base name of the executable that will be launched after run this script.
# CUSTOM_SCRIPT_BLOCK - This is code from the customScript option
# RUN_COMMAND - This is command for run application. Requred BASE_DIR variable.
#
# ####################################################################

export XDG_RUNTIME_DIR=/run/user/0
export QT_QPA_PLATFORM=wayland
export QML_IMPORT_PATH=/usr/lib/qml/
export QML2_IMPORT_PATH=/usr/lib/qml/
export QT_PLUGIN_PATH=/usr/lib/plugins/
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/plugins/platforms

BASE_DIR=$(dirname "$(readlink -f "$0")")
export PATH="$BASE_DIR"/bin/:$PATH
export LD_LIBRARY_PATH="$BASE_DIR"/lib/:"$BASE_DIR":$LD_LIBRARY_PATH
export QML_IMPORT_PATH="$BASE_DIR"/qml/:$QML_IMPORT_PATH
export QML2_IMPORT_PATH="$BASE_DIR"/qml/:$QML2_IMPORT_PATH
export QT_PLUGIN_PATH="$BASE_DIR"/plugins/:$QT_PLUGIN_PATH
export QTWEBENGINEPROCESS_PATH="$BASE_DIR"/bin/QtWebEngineProcess
export QTDIR="$BASE_DIR"
export CQT_PKG_ROOT="$BASE_DIR"
export CQT_RUN_FILE="$BASE_DIR/monitor.sh"

#export QT_QPA_PLATFORM_PLUGIN_PATH="$BASE_DIR"/plugins//platforms:$QT_QPA_PLATFORM_PLUGIN_PATH


"$BASE_DIR/bin/host" "$@"
```
Is it possible to add similar functionality?
Thank you very much.

**Comment by pzhlkj6612** [comment]
Hi.

A question: the environment has Qt pre-installed, so why do you need to package your software with CQtdeployer? I mean, you seem to be able to directly run your software on your platform, don't you?

**Comment by kasonyin** [comment]
Thank you for your reply. 
My project was previously running on a platform without Qt installed. Now, with the addition of a new embedded platform, I need to build packages for both platforms simultaneously. Therefore, I would like to continue with my previous workflow.
maybe modifying my startup script might be more convenient.

**Comment by EndrII** [comment]
> My software runs on an embedded platform where the Qt libraries have already been pre-deployed in the `/usr/lib`. I would like to modify the startup script to include environment variables such as QT_PLUGIN_PATH and QT_QPA_PLATFORM_PLUGIN_PATH, or allow me to add some environment variables in the startup script, like this:
> 
> ```
> #!/bin/sh
> 
> # This is default bat run script of The CQtDeployer project.
> # This file contains key word that will replaced after deploy project.
> #
> # ####################################################################
> #
> # All variables has the CQT_ prefix
> # BIN_PATH - are releative path to executable files of a deployed distribution.
> # LIB_PATH - are releative path to libraryes of a deployed distribution.
> # QML_PATH - are releative path to qml libraryes of a deployed distribution.
> # PLUGIN_PATH - are releative path to qt plugins of a deployed distribution.
> # BIN_PATH - are releative path to targets of a deployed distribution.
> 
> # SYSTEM_LIB_PATH - are releative path to system libraryes of a deployed distribution.
> # BASE_NAME - are base name of the executable that will be launched after run this script.
> # CUSTOM_SCRIPT_BLOCK - This is code from the customScript option
> # RUN_COMMAND - This is command for run application. Requred BASE_DIR variable.
> #
> # ####################################################################
> 
> export XDG_RUNTIME_DIR=/run/user/0
> export QT_QPA_PLATFORM=wayland
> export QML_IMPORT_PATH=/usr/lib/qml/
> export QML2_IMPORT_PATH=/usr/lib/qml/
> export QT_PLUGIN_PATH=/usr/lib/plugins/
> export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/plugins/platforms
> 
> BASE_DIR=$(dirname "$(readlink -f "$0")")
> export PATH="$BASE_DIR"/bin/:$PATH
> export LD_LIBRARY_PATH="$BASE_DIR"/lib/:"$BASE_DIR":$LD_LIBRARY_PATH
> export QML_IMPORT_PATH="$BASE_DIR"/qml/:$QML_IMPORT_PATH
> export QML2_IMPORT_PATH="$BASE_DIR"/qml/:$QML2_IMPORT_PATH
> export QT_PLUGIN_PATH="$BASE_DIR"/plugins/:$QT_PLUGIN_PATH
> export QTWEBENGINEPROCESS_PATH="$BASE_DIR"/bin/QtWebEngineProcess
> export QTDIR="$BASE_DIR"
> export CQT_PKG_ROOT="$BASE_DIR"
> export CQT_RUN_FILE="$BASE_DIR/monitor.sh"
> 
> #export QT_QPA_PLATFORM_PLUGIN_PATH="$BASE_DIR"/plugins//platforms:$QT_QPA_PLATFORM_PLUGIN_PATH
> 
> 
> "$BASE_DIR/bin/host" "$@"
> ```
> 
> Is it possible to add similar functionality? Thank you very much.

I think standard script should works fine in your situations but, if you want to add custom code to your script just override them using -**customScript** or -[runScript](https://github.com/QuasarApp/CQtDeployer/blob/main/src/Deploy/src/ScriptsTemplates/linux.sh) options 

You can take our template script from GitHub - add your code and include to your deployment command 

```
cqtdeployer -customScript "export myVariable = 1"
```

or 
```
cqtdeployer -runScript "path/to/new/script"
```

**Comment by EndrII** [comment]
@kasonyin close this issue if your case is solved)

**Comment by kasonyin** [comment]
> @kasonyin close this issue if your case is solved)

Okay, thanks for your suggestion

**Comment by pzhlkj6612** [comment]
@kasonyin , does `-customScript` work?

**Comment by kasonyin** [comment]
> @kasonyin , does `-customScript` work?

Yes, -customScript does work.
